### ISSUE TITLE
mmcv:grid_sampler(-1) is not a registered function/op

### ISSUE THREAD

**Issue by w5688414** [open-mmlab/mmediting#1004]
I meet a problem when I try to convert vsr model to onnx:

```
/lyf/mmediting/mmedit/models/backbones/sr_backbones/basicvsr_pp.py:283:0
  %output : Float(*, *, *, *, *, strides=[8242560, 2747520, 915840, 1272, 1], requires_grad=0, device=cpu) = onnx::Concat[axis=1, onnx_name="Concat_4356"](%onnx::Concat_4835, %onnx::Concat_4836, %onnx::Concat_4837) # /home/lyf/mmediting/mmedit/models/backbones/sr_backbones/basicvsr_pp.py:283:0
  return (%output)

Successfully exported ONNX model: basicvsr.onnx
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 200, in <module>
    pytorch2onnx(
  File "tools/pytorch2onnx.py", line 98, in pytorch2onnx
    sess = rt.InferenceSession(output_file)
  File "/home/infname112/anaconda3/envs/mmedit/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/infname112/anaconda3/envs/mmedit/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from basicvsr.onnx failed:Fatal error: mmcv:grid_sampler(-1) is not a registered function/op
```

here is my command:

```
python tools/pytorch2onnx.py \
    configs/restorers/basicvsr_plusplus/basicvsr_plusplus_c64n7_8x1_600k_reds4.py \
    checkpoints/basicvsr_plusplus_c64n7_8x1_600k_reds4_20210217-db622b2f.pth \
    restorer \
    udm10/BDx4 \
    --output-file basicvsr.onnx \
    --show \
    --verify \
    --dynamic-export
```

**Comment by w5688414** [comment]
It seems that when I try to convert to convert basic_vsr.onnx to om model, None output, here is the log:

```
t of EngineManager::Finalize is [37] micro second."
[INFO] GE(52121,atc.bin):2022-08-10-16:12:33.145.792 [gelib.cc:458]52121 Finalize:VarManagerPool finalization.
[INFO] GE(52121,atc.bin):2022-08-10-16:12:33.145.821 [gelib.cc:461]52121 Finalize:HostCpuEngine finalization.
[INFO] GE(52121,atc.bin):2022-08-10-16:12:33.145.834 [host_cpu_engine.cc:115]52121 Finalize:start HostCpuEngine::Finalize
[INFO] GE(52121,atc.bin):2022-08-10-16:12:33.145.846 [gelib.cc:464]52121 Finalize:Analyzer finalization
[DEBUG] GE(52121,atc.bin):2022-08-10-16:12:33.145.858 [analyzer.cc:115]52121 Finalize:Analyzer start to finalize!
[INFO] GE(52121,atc.bin):2022-08-10-16:12:33.145.874 [process_node_engine_manager.cc:87]52121 Finalize:ProcessNodeEngine id:HOST_CPU.
[INFO] GE(52121,atc.bin):2022-08-10-16:12:33.145.888 [process_node_engine_manager.cc:87]52121 Finalize:ProcessNodeEngine id:NPU.
[DEBUG] GE(52121,atc.bin):2022-08-10-16:12:33.145.924 [node_compile_cache_module.cc:442]52121 Finalize:Finalize ccm.
[INFO] GE(52121,atc.bin):2022-08-10-16:12:33.145.937 [gelib.cc:495]52121 Finalize:finalization success.
[WARNING] GE(52121,atc.bin):2022-08-10-16:12:33.145.972 [graph_manager.cc:250]52121 Finalize:GraphManager has not been initialized.
[WARNING] GE(52121,atc.bin):2022-08-10-16:12:33.146.008 [main_impl.cc:1368]52121 CheckRet:ATC generate offline model failed.
ATC run failed, Make sure this is what you want: '--mode=0'. Please check the detail log, Try 'atc --help' for more information
[INFO] GE(52121,atc.bin):2022-08-10-16:12:33.146.044 [error_manager.cc:343]52121 GetErrorMessage:current work_stream_id:5212152121
E16005: The model has [2] [--domain_version] fields, but only one is allowed.
        Model parse to graph failed, graph name:basicvsr.[FUNC:ModelParseToGraph][FILE:onnx_parser.cc][LINE:847]
        ATC model parse ret fail.[FUNC:ParseGraph][FILE:omg.cc][LINE:787]

[INFO] GE(52121,atc.bin):2022-08-10-16:12:33.146.446 [main_impl.cc:1450]52121 GetMemInfo:Find mem [MemAvailable] info line [MemAvailable:   457220344 kB]
```

**Comment by zengyh1900** [comment]
Please check this issue. @plyfager

**Comment by plyfager** [comment]
We'll have a look.You may also put forward an issue in https://github.com/open-mmlab/mmdeploy for help.

**Comment by hanrui1sensetime** [comment]
Hi, @w5688414. Still have this issue? Please open a issue on [mmdeploy](https://github.com/open-mmlab/mmdeploy)

**Comment by zengyh1900** [comment]
Closing due to inactivity, please reopen if there are any further problems.

**Comment by kesssssa** [comment]
你能成功的将basicvsr++模型转换成onnx模型吗？我在这里遇到了问题，能否请教你
