### ISSUE TITLE
FileNotFoundError: work_dirs/101_RRDBNet/101_RRDBNet_iter_1000000.pth can not be found.

### ISSUE THREAD

**Issue by fujintao1999** [open-mmlab/mmediting#1077]
2022-09-03 01:38:02,141 - mmedit - INFO - Set random seed to 448216529, deterministic: False
2022-09-03 01:38:04,811 - mmedit - INFO - load checkpoint from torchvision path: torchvision://vgg19
2022-09-03 01:38:31,562 - mmedit - INFO - load checkpoint from local path: work_dirs/101_RRDBNet/101_RRDBNet_iter_1000000.pth
Traceback (most recent call last):
  File "tools/train.py", line 169, in <module>
    main()
  File "tools/train.py", line 165, in main
    meta=meta)
  File "/workspace/mmediting/mmedit/apis/train.py", line 112, in train_model
    meta=meta)
  File "/workspace/mmediting/mmedit/apis/train.py", line 360, in _non_dist_train
    runner.load_checkpoint(cfg.load_from)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py", line 355, in load_checkpoint
    revise_keys=revise_keys)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/checkpoint.py", line 627, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/checkpoint.py", line 561, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/checkpoint.py", line 303, in load_checkpoint
    return checkpoint_loader(filename, map_location)  # type: ignore
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/checkpoint.py", line 322, in load_from_local
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: work_dirs/101_RRDBNet/101_RRDBNet_iter_1000000.pth can not be found.

**Comment by zengyh1900** [comment]
Please check this issue. @Z-Fran

**Comment by Z-Fran** [comment]
Sorry for the late reply. Did you check checkpoint file existing and your working directory?
