### ISSUE TITLE
how to make an annotation file of sub-images in a dataset for restoration?

### ISSUE THREAD

**Issue by satoshils** [open-mmlab/mmediting#125]
https://github.com/open-mmlab/mmediting/blob/master/docs/datasets_restoration.md
This md says an annotation file should contains the image names and image shape,but what is "image shape" meaning?Is that means the resolution？
There is also an example:
0001_s001.png (480,480,3)
0001_s002.png (480,480,3)
What are 480,480,3 mean?Are 480,480 suppose to be resolution?What's the "3"?

PS:Sorry for my poor English

**Comment by satoshils** [comment]
Then I change the dataset folders' name DIV2K_train_HR_SUB and x4 to DIV2K_train_HR and x4,run the training of ESRGAN again.
The log says "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpoqzi_vc2/tmpg3dp7ii7.py'",what should I do?
The training is with a single gpu,my training code is 'python tools/train.py configs/restorers/esrgan/esrgan_x4c64b23g32_g1_400k_div2k.py'.
And this is the log
`Traceback (most recent call last):
  File "tools/train.py", line 137, in <module>
    main()
  File "tools/train.py", line 60, in main
    cfg = Config.fromfile(args.config)
  File "/home/satoshibx/.local/lib/python3.8/site-packages/mmcv/utils/config.py", line 210, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/home/satoshibx/.local/lib/python3.8/site-packages/mmcv/utils/config.py", line 142, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/satoshibx/anaconda3/envs/open-mmlab/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpoqzi_vc2/tmpg3dp7ii7.py", line 100, in <module>
NameError: name 'none' is not defined
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f3fc58563a0>
Traceback (most recent call last):
  File "/home/satoshibx/anaconda3/envs/open-mmlab/lib/python3.8/tempfile.py", line 441, in __del__
    self.close()
  File "/home/satoshibx/anaconda3/envs/open-mmlab/lib/python3.8/tempfile.py", line 437, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpoqzi_vc2/tmpg3dp7ii7.py'`

Am I do something wrong?

**Comment by xinntao** [comment]
For the annotation file, here is the example
```python
import mmcv
from os import path as osp
from PIL import Image


def generate_meta_info_div2k():
    """Generate meta info for DIV2K dataset.
    """

    gt_folder = 'datasets/DIV2K/DIV2K_train_HR_sub/'
    meta_info_txt = 'basicsr/data/meta_info/meta_info_DIV2K800sub_GT.txt'

    img_list = sorted(list(mmcv.scandir(gt_folder)))

    with open(meta_info_txt, 'w') as f:
        for idx, img_path in enumerate(img_list):
            img = Image.open(osp.join(gt_folder, img_path))  # lazy load
            width, height = img.size
            mode = img.mode
            if mode == 'RGB':
                n_channel = 3
            elif mode == 'L':
                n_channel = 1
            else:
                raise ValueError(f'Unsupported mode {mode}.')

            info = f'{img_path} ({height},{width},{n_channel})'
            print(idx + 1, info)
            f.write(f'{info}\n')


if __name__ == '__main__':
    generate_meta_info_div2k()
```
