### ISSUE TITLE
Running matting inference demo without GPU

### ISSUE THREAD

**Issue by Joaquim-Ferrer** [open-mmlab/mmediting#130]
As far as I understand all the features required to run matting inference are implemented without GPU. 

What I did was to make sure in the demo file that the device passed was torch.device("cpu") and remove the scatter function call in mmedit/apis/matting_inference.py (Probably this causes the following error but I can't find documentation for it to understand what it does).

```
Traceback (most recent call last):
  File "demo/matting_demo.py", line 38, in <module>
    main()
  File "demo/matting_demo.py", line 30, in main
    args.trimap_path) * 255
  File "/home/jvrbferrer/mmediting/mmedit/apis/matting_inference.py", line 74, in matting_inference
    result = model(test_mode=True, **data)
  File "/home/jvrbferrer/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _c
all_impl
    result = self.forward(*input, **kwargs)
  File "/home/jvrbferrer/mmediting/mmedit/models/mattors/base_mattor.py", line 268, in forward
    return self.forward_test(merged, trimap, meta, **kwargs)
  File "/home/jvrbferrer/mmediting/mmedit/models/mattors/dim.py", line 143, in forward_test
    torch.cat((merged, trimap), 1), self.test_cfg.refine)
RuntimeError: Sizes of tensors must match except in dimension 1. Got 3 and 1 in dimension 0 (The offending index is 1
```

**Comment by hejm37** [comment]
Hi, Joaquim! Maybe you have also removed the `collate` function which is at the same line as `scatter`. To fix it, you may need to keep `collate` function.

The `collate` function will deal with the dimension of the Tensors while `scatter` function will put the processed Tensors to the right devices.

**Comment by hejm37** [comment]
If there is no further problem, I will close this issue.
