### ISSUE TITLE
[Bug] `GenerateFacialHeatmap` may return heatmap in `float64`

### ISSUE THREAD

**Issue by LeoXing1996** [open-mmlab/mmediting#1309]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmediting/tree/1.x

### Environment

```
pytorch-1.11.0-pytorch
mmcv-2.0.0-rc1
mmengine-0.1.0
```

### Reproduces the problem - code sample

```python
    def transform(self, results):
        img = results[self.image_key]

        if self.use_cache:
            hash_key = f"{self.image_key}_{results['key']}"
            if hash_key in self.cache:
                heatmap = self.cache[hash_key]
            else:
                heatmap = self.generate_heatmap_from_img(img)
                self.cache[hash_key] = heatmap
        else:
            heatmap = self.generate_heatmap_from_img(img)

        results[f'{self.image_key}_heatmap'] = heatmap

        return results
```

### Reproduces the problem - command or script

```bash
bash tools/slurm_train.sh mm_lol dic-debug configs_ceph/dic/dic_gan-x8c48b6_4xb2-500k_celeba-hq.py work_dirs/dic-debug
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    main()
  File "tools/train.py", line 108, in main
    runner.train()
  File "/mnt/petrelfs/xingzhening/mmengine/mmengine/runner/runner.py", line 1641, in train
    model = self.train_loop.run()  # type: ignore
  File "/mnt/petrelfs/xingzhening/mmengine/mmengine/runner/loops.py", line 260, in run
    self.run_iter(data_batch)
  File "/mnt/petrelfs/xingzhening/mmengine/mmengine/runner/loops.py", line 283, in run_iter
    outputs = self.runner.model.train_step(
  File "/mnt/petrelfs/xingzhening/mmengine/mmengine/model/wrappers/seperate_distributed.py", line 101, in train_step
    return self.module.train_step(data, optim_wrapper)
  File "/mnt/petrelfs/xingzhening/mmediting-test-1.x/mmedit/models/editors/srgan/srgan.py", line 300, in train_step
    log_vars_d = self.g_step_with_optim(
  File "/mnt/petrelfs/xingzhening/mmediting-test-1.x/mmedit/models/editors/srgan/srgan.py", line 212, in g_step_with_optim
    g_optim_wrapper.update_params(parsed_losses_g)
  File "/mnt/petrelfs/xingzhening/mmengine/mmengine/optim/optimizer/optimizer_wrapper.py", line 130, in update_params
    self.backward(loss)
  File "/mnt/petrelfs/xingzhening/mmengine/mmengine/optim/optimizer/optimizer_wrapper.py", line 154, in backward
    loss.backward(**kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt111-cu113/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt111-cu113/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Found dtype Double but expected Float
```

**Comment by zengyh1900** [comment]
Fixed in https://github.com/open-mmlab/mmediting/pull/1310
