### ISSUE TITLE
[Bug] ttsr config in master branch

### ISSUE THREAD

**Issue by liuky74** [open-mmlab/mmediting#1426]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmediting

### Environment

Don't need that

### Reproduces the problem - code sample

```python
# file: configs/restorers/ttsr/ttsr-rec_x4_c64b16_g1_200k_CUFED.py
........
# optimizer, I think there should be `optimizers = dict(generator=dict(type='Adam', lr=1.e-4))`
optimizers = dict(type='Adam', lr=1.e-4)

# learning policy
total_iters = 200000
lr_config = dict(policy='Step', by_epoch=False, step=[100000], gamma=0.5)
..........
```

### Reproduces the problem - command or script

```shell
python ./tools/train.py configs/restorers/ttsr/ttsr-rec_x4_c64b16_g1_200k_CUFED.py
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "/home/smartgis/anaconda3/envs/mmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/smartgis/anaconda3/envs/mmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/smartgis/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/smartgis/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/smartgis/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/smartgis/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/smartgis/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/smartgis/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/smartgis/workspace/project/mmlab/mmediting/tools/train.py", line 173, in <module>
    main()
  File "/home/smartgis/workspace/project/mmlab/mmediting/tools/train.py", line 162, in main
    train_model(
  File "/home/smartgis/workspace/project/mmlab/mmediting/mmedit/apis/train.py", line 106, in train_model
    _non_dist_train(
  File "/home/smartgis/workspace/project/mmlab/mmediting/mmedit/apis/train.py", line 362, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/smartgis/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/smartgis/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/smartgis/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/smartgis/workspace/project/mmlab/mmediting/mmedit/models/restorers/ttsr.py", line 184, in train_step
    optimizer['generator'].zero_grad()
TypeError: 'Adam' object is not subscriptable
```

### Additional information

There is an error in the TTSR configuration file "configs/restorers/ttsr/ttsr-rec_x4_c64b16_g1_200k_CUFED.py"

optimizer config should be  "optimizers = dict(generator=dict(type='Adam', lr=1.e-4))" ?

---
TTSR 不使用GAN的配置文件"ttsr-rec_x4_c64b16_g1_200k_CUFED.py"中的optimizers配置有误

**Comment by liuwenran** [comment]
@liuky74 I think you are right.  You could submit a pull request to fix this. Btw, master branch of mmeding is a bit outdated, and it is highly recommended to use 1.x branch which is now under development and updated more frequently. :blush:

**Comment by liuwenran** [comment]
pr submitted #1435
