### ISSUE TITLE
ImportError: cannot import name 'collect_env' from 'mmcv.utils'

### ISSUE THREAD

**Issue by stoneyang159** [open-mmlab/mmediting#155]
我使用以下命令安装mmediting：
```
pip install -r requirements.txt --use-feature=2020-resolver
pip install -v -e . 
```

使用如下命令训练：
./tools/dist_train.sh configs/inpainting/partial_conv/pconv_256x256_stage1_8x1_places.py 2

遇到了错误：
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "./tools/train.py", line 16, in <module>
    from mmedit.utils import collect_env, get_root_logger
  File "/home/lhw/workspace/yz/mmediting/mmedit/utils/collect_env.py", line 1, in <module>
    from mmcv.utils import collect_env as collect_base_env
ImportError: cannot import name 'collect_env' from 'mmcv.utils' (/home/lhw/anaconda3/lib/python3.7/site-packages/mmcv/utils/__init__.py)
Traceback (most recent call last):
  File "./tools/train.py", line 16, in <module>
    from mmedit.utils import collect_env, get_root_logger
  File "/home/lhw/workspace/yz/mmediting/mmedit/utils/collect_env.py", line 1, in <module>
    from mmcv.utils import collect_env as collect_base_env
ImportError: cannot import name 'collect_env' from 'mmcv.utils' (/home/lhw/anaconda3/lib/python3.7/site-packages/mmcv/utils/__init__.py)
Traceback (most recent call last):
  File "/home/lhw/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lhw/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lhw/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/lhw/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/lhw/anaconda3/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/inpainting/partial_conv/pconv_256x256_stage1_8x1_places.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

附上pip install -r requirements.txt --use-feature=2020-resolver时打印的内容
``` 
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: lmdb in /home/lhw/anaconda3/lib/python3.7/site-packages (from -r requirements/runtime.txt (line 1)) (1.0.0)
WARNING: Keyring is skipped due to an exception: Failed to unlock the collection!
Requirement already satisfied: mmcv-full>=1.0.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from -r requirements/runtime.txt (line 2)) (1.1.0)
Requirement already satisfied: scikit-image in /home/lhw/anaconda3/lib/python3.7/site-packages (from -r requirements/runtime.txt (line 3)) (0.16.2)
Requirement already satisfied: tensorboard in /home/lhw/anaconda3/lib/python3.7/site-packages (from -r requirements/runtime.txt (line 4)) (1.15.0)
Requirement already satisfied: yapf in /home/lhw/anaconda3/lib/python3.7/site-packages (from -r requirements/runtime.txt (line 5)) (0.30.0)
Requirement already satisfied: codecov in /home/lhw/anaconda3/lib/python3.7/site-packages (from -r requirements/tests.txt (line 1)) (2.1.10)
Requirement already satisfied: flake8 in /home/lhw/anaconda3/lib/python3.7/site-packages (from -r requirements/tests.txt (line 2)) (3.8.3)
Requirement already satisfied: interrogate in /home/lhw/anaconda3/lib/python3.7/site-packages (from -r requirements/tests.txt(line 3)) (1.3.2)
Requirement already satisfied: isort==4.3.21 in /home/lhw/anaconda3/lib/python3.7/site-packages (from -r requirements/tests.txt (line 4)) (4.3.21)
Requirement already satisfied: pytest in /home/lhw/anaconda3/lib/python3.7/site-packages (from -r requirements/tests.txt (line 5)) (5.4.3)
Requirement already satisfied: pytest-runner in /home/lhw/anaconda3/lib/python3.7/site-packages (from -r requirements/tests.txt (line 6)) (5.2)
Requirement already satisfied: py in /home/lhw/anaconda3/lib/python3.7/site-packages (from interrogate->-r requirements/tests.txt (line 3)) (1.9.0)
Requirement already satisfied: toml in /home/lhw/anaconda3/lib/python3.7/site-packages (from interrogate->-r requirements/tests.txt (line 3)) (0.10.1)
Requirement already satisfied: colorama in /home/lhw/anaconda3/lib/python3.7/site-packages (from interrogate->-r requirements/tests.txt (line 3)) (0.4.3)
Requirement already satisfied: tabulate in /home/lhw/anaconda3/lib/python3.7/site-packages (from interrogate->-r requirements/tests.txt (line 3)) (0.8.6)
Requirement already satisfied: click in /home/lhw/anaconda3/lib/python3.7/site-packages (from interrogate->-r requirements/tests.txt (line 3)) (7.1.2)
Requirement already satisfied: attrs in /home/lhw/anaconda3/lib/python3.7/site-packages (from interrogate->-r requirements/tests.txt (line 3)) (19.3.0)
Requirement already satisfied: addict in /home/lhw/anaconda3/lib/python3.7/site-packages (from mmcv-full>=1.0.0->-r requirements/runtime.txt (line 2)) (2.2.1)
Requirement already satisfied: pyyaml in /home/lhw/anaconda3/lib/python3.7/site-packages (from mmcv-full>=1.0.0->-r requirements/runtime.txt (line 2)) (5.3.1)
Requirement already satisfied: opencv-python-headless>=3 in /home/lhw/anaconda3/lib/python3.7/site-packages (from mmcv-full>=1.0.0->-r requirements/runtime.txt (line 2)) (4.2.0.32)
Requirement already satisfied: numpy in /home/lhw/anaconda3/lib/python3.7/site-packages (from mmcv-full>=1.0.0->-r requirements/runtime.txt (line 2)) (1.18.5)
Requirement already satisfied: yapf in /home/lhw/anaconda3/lib/python3.7/site-packages (from -r requirements/runtime.txt (line 5)) (0.30.0)
Requirement already satisfied: wheel>=0.26 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (0.34.2)
Requirement already satisfied: absl-py>=0.4 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (0.9.0)
Requirement already satisfied: werkzeug>=0.11.15 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (1.0.1)
Requirement already satisfied: six>=1.10.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (1.15.0)
Requirement already satisfied: protobuf>=3.6.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (3.11.3)
Requirement already satisfied: setuptools>=41.0.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (50.3.0)
Requirement already satisfied: grpcio>=1.6.3 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (1.27.1)
Requirement already satisfied: numpy in /home/lhw/anaconda3/lib/python3.7/site-packages (from mmcv-full>=1.0.0->-r requirements/runtime.txt (line 2)) (1.18.5)
Requirement already satisfied: markdown>=2.6.8 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (3.2)
Requirement already satisfied: six>=1.10.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (1.15.0)
Requirement already satisfied: setuptools>=41.0.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (50.3.0)
Requirement already satisfied: six>=1.10.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (1.15.0)
Requirement already satisfied: setuptools>=41.0.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (50.3.0)
Requirement already satisfied: scipy>=0.19.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from scikit-image->-r requirements/runtime.txt (line 3)) (1.5.0)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from scikit-image->-r requirements/runtime.txt (line 3)) (3.0.2)
Requirement already satisfied: pillow>=4.3.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from scikit-image->-r requirements/runtime.txt (line 3)) (6.2.2)
Requirement already satisfied: networkx>=2.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from scikit-image->-r requirements/runtime.txt (line 3)) (2.4)
Requirement already satisfied: PyWavelets>=0.4.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from scikit-image->-r requirements/runtime.txt (line 3)) (1.1.1)
Requirement already satisfied: imageio>=2.3.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from scikit-image->-r requirements/runtime.txt (line 3)) (2.9.0)
Requirement already satisfied: decorator>=4.3.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from networkx>=2.0->scikit-image->-r requirements/runtime.txt (line 3)) (4.4.2)
Requirement already satisfied: pillow>=4.3.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from scikit-image->-r requirements/runtime.txt (line 3)) (6.2.2)
Requirement already satisfied: numpy in /home/lhw/anaconda3/lib/python3.7/site-packages (from mmcv-full>=1.0.0->-r requirements/runtime.txt (line 2)) (1.18.5)
Requirement already satisfied: numpy in /home/lhw/anaconda3/lib/python3.7/site-packages (from mmcv-full>=1.0.0->-r requirements/runtime.txt (line 2)) (1.18.5)
Requirement already satisfied: numpy in /home/lhw/anaconda3/lib/python3.7/site-packages (from mmcv-full>=1.0.0->-r requirements/runtime.txt (line 2)) (1.18.5)
Requirement already satisfied: numpy in /home/lhw/anaconda3/lib/python3.7/site-packages (from mmcv-full>=1.0.0->-r requirements/runtime.txt (line 2)) (1.18.5)
Requirement already satisfied: python-dateutil>=2.1 in /home/lhw/anaconda3/lib/python3.7/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->-r requirements/runtime.txt (line 3)) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/lhw/anaconda3/lib/python3.7/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->-r requirements/runtime.txt (line 3)) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /home/lhw/anaconda3/lib/python3.7/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->-r requirements/runtime.txt (line 3)) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/lhw/anaconda3/lib/python3.7/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->-r requirements/runtime.txt (line 3)) (2.4.7)
Requirement already satisfied: six>=1.10.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (1.15.0)
Requirement already satisfied: six>=1.10.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (1.15.0)
Requirement already satisfied: numpy in /home/lhw/anaconda3/lib/python3.7/site-packages (from mmcv-full>=1.0.0->-r requirements/runtime.txt (line 2)) (1.18.5)
Requirement already satisfied: six>=1.10.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (1.15.0)
Requirement already satisfied: pycodestyle<2.7.0,>=2.6.0a1 in /home/lhw/anaconda3/lib/python3.7/site-packages (from flake8->-r requirements/tests.txt (line 2)) (2.6.0)
Requirement already satisfied: importlib-metadata in /home/lhw/anaconda3/lib/python3.7/site-packages (from flake8->-r requirements/tests.txt (line 2)) (1.7.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from flake8->-r requirements/tests.txt (line 2)) (0.6.1)
Requirement already satisfied: pyflakes<2.3.0,>=2.2.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from flake8->-r requirements/tests.txt (line 2)) (2.2.0)
Requirement already satisfied: zipp>=0.5 in /home/lhw/anaconda3/lib/python3.7/site-packages (from importlib-metadata->flake8->-r requirements/tests.txt (line 2)) (3.1.0)
Requirement already satisfied: coverage in /home/lhw/anaconda3/lib/python3.7/site-packages (from codecov->-r requirements/tests.txt (line 1)) (5.3)
Requirement already satisfied: requests>=2.7.9 in /home/lhw/anaconda3/lib/python3.7/site-packages (from codecov->-r requirements/tests.txt (line 1)) (2.24.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/lhw/anaconda3/lib/python3.7/site-packages (from requests>=2.7.9->codecov->-r requirements/tests.txt (line 1)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/lhw/anaconda3/lib/python3.7/site-packages (from requests>=2.7.9->codecov->-r requirements/tests.txt (line 1)) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /home/lhw/anaconda3/lib/python3.7/site-packages (from requests>=2.7.9->codecov->-r requirements/tests.txt (line 1)) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /home/lhw/anaconda3/lib/python3.7/site-packages (from requests>=2.7.9->codecov->-r requirements/tests.txt (line 1)) (2.10)
Requirement already satisfied: py in /home/lhw/anaconda3/lib/python3.7/site-packages (from interrogate->-r requirements/tests.txt (line 3)) (1.9.0)
Requirement already satisfied: packaging in /home/lhw/anaconda3/lib/python3.7/site-packages (from pytest->-r requirements/tests.txt (line 5)) (20.4)
Requirement already satisfied: attrs in /home/lhw/anaconda3/lib/python3.7/site-packages (from interrogate->-r requirements/tests.txt (line 3)) (19.3.0)
Requirement already satisfied: more-itertools>=4.0.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from pytest->-r requirements/tests.txt (line 5)) (8.4.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in /home/lhw/anaconda3/lib/python3.7/site-packages (from pytest->-r requirements/tests.txt (line 5)) (0.13.1)
Requirement already satisfied: wcwidth in /home/lhw/anaconda3/lib/python3.7/site-packages (from pytest->-r requirements/tests.txt (line 5)) (0.2.5)
Requirement already satisfied: importlib-metadata in /home/lhw/anaconda3/lib/python3.7/site-packages (from flake8->-r requirements/tests.txt (line 2)) (1.7.0)
Requirement already satisfied: importlib-metadata in /home/lhw/anaconda3/lib/python3.7/site-packages (from flake8->-r requirements/tests.txt (line 2)) (1.7.0)
Requirement already satisfied: six>=1.10.0 in /home/lhw/anaconda3/lib/python3.7/site-packages (from tensorboard->-r requirements/runtime.txt (line 4)) (1.15.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/lhw/anaconda3/lib/python3.7/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->-r requirements/runtime.txt (line 3)) (2.4.7)
WARNING: You are using pip version 20.2.2; however, version 20.2.4 is available.
You should consider upgrading via the '/home/lhw/anaconda3/bin/python -m pip install --upgrade pip' command.
```

**Comment by nbei** [comment]
Hi @stoneyang159 , I think the reason is that you have not installed the PyTorch. You may install PyTorch and have a try. I'm confused about the PyTorch missing from you installation and you may have a double check.

----------------------------------------------------------

Hi @stoneyang159 , 我认为一个可能的原因是你没有安装 `PyTorch`。 你可以尝试先安装一下 `PyTorch` 并且再重新安装我们的工具。不过我并不理解为什么 `PyTorch` 会在你的安装过程中没有安装，你可以再次确认一下。

**Comment by stoneyang159** [comment]
@nbei  感谢回复，我的环境里安装的是pytorch1.7，我用pip list确认了一下
```
(base) lhw@czcv:~/workspace/yz/pytorch-inpainting-with-partial-conv$ pip list | grep torch
efficientnet-pytorch               0.6.3
fer-pytorch                        0.1.0
guided-filter-pytorch              3.7.5
pytorchcv                          0.0.57
torch                              1.7.0.dev20200721
torchfile                          0.1.0
torchvision                        0.8.0.dev20200721
```

然后我检查了一下我安装的mmcv
```
(base) lhw@czcv:~/workspace/yz/pytorch-inpainting-with-partial-conv$ python
Python 3.7.7 (default, May  7 2020, 21:25:33)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mmcv
>>> from mmcv.utils import collect_env
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'collect_env' from 'mmcv.utils' (/home/lhw/anaconda3/lib/python3.7/site-packages/mmcv/utils/__init__.py)
>>>
(base) lhw@czcv:~/workspace/yz/pytorch-inpainting-with-partial-conv$ cd /home/lhw/anaconda3/lib/python3.7/site-packages/mmcv/utils
(base) lhw@czcv:~/anaconda3/lib/python3.7/site-packages/mmcv/utils$ ls
config.py  ext_loader.py  logging.py  parrots_wrapper.py  progressbar.py  registry.py  version_utils.py
env.py     __init__.py    misc.py     path.py             __pycache__     timer.py
(base) lhw@czcv:~/anaconda3/lib/python3.7/site-packages/mmcv/utils$ vi __
__init__.py  __pycache__/
(base) lhw@czcv:~/anaconda3/lib/python3.7/site-packages/mmcv/utils$ vi __init__.py
(base) lhw@czcv:~/anaconda3/lib/python3.7/site-packages/mmcv/utils$
```
在 mmcv/utils/__init__.py 内部没有搜索到collect_env，而https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/__init__.py这里是有collect_env的。
稍后我会尝试通过源码安装mmcv试试

**Comment by stoneyang159** [comment]
我重新clone了一下代码，然后没问题了
