### ISSUE TITLE
Training pconv results in "AssertionError: Default process group is not initialized"

### ISSUE THREAD

**Issue by styler00dollar** [open-mmlab/mmediting#156]
Starting pconv inpainting training with the default configuration and changed file paths results in this error message:
```
python tools/train.py configs/inpainting/partial_conv/custom.py
[...]
2020-11-11 03:21:45,481 - mmedit - INFO - Start running, host: root@61fb20da813e, work_dir: /content/mmediting/work_dirs/test_pggan
2020-11-11 03:21:45,481 - mmedit - INFO - workflow: [('train', 10000)], max: 300002 iters
2020-11-11 03:21:45.736864: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "tools/train.py", line 145, in <module>
    main()
  File "tools/train.py", line 141, in main
    meta=meta)
  File "/content/mmediting/mmedit/apis/train.py", line 78, in train_model
    meta=meta)
  File "/content/mmediting/mmedit/apis/train.py", line 294, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/content/mmediting/mmedit/models/inpaintors/pconv_inpaintor.py", line 121, in train_step
    fake_res, final_mask = self.generator(masked_img, mask_input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/content/mmediting/mmedit/models/backbones/encoder_decoders/pconv_encoder_decoder.py", line 38, in forward
    x, final_mask = self.decoder(enc_outputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/mmediting/mmedit/models/backbones/encoder_decoders/decoders/pconv_decoder.py", line 114, in forward
    h, h_mask = getattr(self, dec_l_key)(h, h_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/mmediting/mmedit/models/common/mask_conv_module.py", line 80, in forward
    x = self.norm(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/batchnorm.py", line 519, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 625, in get_world_size
    return _get_group_size(group)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 220, in _get_group_size
    _check_default_pg()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 211, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
```
Deepfillv2 seems to work fine.

**Comment by nbei** [comment]
Could you provide the whole command line for the training.

**Comment by styler00dollar** [comment]
I am not really sure what you mean, since I pasted the full command that I used. I start the train.py file with python and only point to a config file. That approach works fine for deepfillv2.

**Comment by nbei** [comment]
As described in our docs, you need to use distributed training rather than directly `python train.py ...`.

**Comment by styler00dollar** [comment]
I remember that I tried to run the suggested way with ``dist_train.sh`` in the past and I failed to get it working. I retried it today and it works.
```
%cd /content/mmediting/
# for one GPU
!./tools/dist_train.sh /content/mmediting/configs/inpainting/partial_conv/custom.py 1
```
I am not that sure why this never worked in the past, but it works now. But it is still interesting that pconv does not work, but deepfillv2 is working by simply using ``train.py``. Closing this issue since training is possible without major problems.
