### ISSUE TITLE
MaxUnpool2d  NotImplementedError

### ISSUE THREAD

**Issue by La-fe** [open-mmlab/mmediting#168]
My environment is pytorch 1.4, mmcv 1.2.1 mmedit 0.5, cuda10.1 
When I run configs/mattors/dim/dim_stage1_v16_1x1_1000k_comp1k.py for training, it will appear

------------------------------------------------------------------------------------
2020-12-03 11:13:40,133 - mmedit - INFO - workflow: [('train', 1)], max: 1000000 iters
Traceback (most recent call last):
  File "tools/train.py", line 148, in <module>
    main()
  File "tools/train.py", line 144, in main
    meta=meta)
  File "/home/lafe/mt/independence_cv/mmediting/mmedit/apis/train.py", line 78, in train_model
    meta=meta)
  File "/home/lafe/mt/independence_cv/mmediting/mmedit/apis/train.py", line 294, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/lafe/.conda/envs/py37pt1.4/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/lafe/.conda/envs/py37pt1.4/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/lafe/.conda/envs/py37pt1.4/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/lafe/mt/independence_cv/mmediting/mmedit/models/mattors/dim.py", line 208, in train_step
    loss.backward()
  File "/home/lafe/.conda/envs/py37pt1.4/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/lafe/.conda/envs/py37pt1.4/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/lafe/.conda/envs/py37pt1.4/lib/python3.7/site-packages/torch/autograd/function.py", line 77, in apply
    return self._forward_cls.backward(self, *args)
  File "/home/lafe/.conda/envs/py37pt1.4/lib/python3.7/site-packages/torch/autograd/function.py", line 181, in backward
    raise NotImplementedError
NotImplementedError

------------------------------------------------------------------------------------
I finally found in class PlainDecoder module 
It calls the modified MaxUnpool2d  (line 105), and MaxUnpool2dop not realizes backward.
I put official implementation of the torch.nn.Modules.Pooling.MaxUnpool2d (kernel size = 2, stride = 2) instead of MaxUnpool2d (kernel size = 2, stride = 2), and then the network can train normally.

**Comment by hejm37** [comment]
Hi, thank you for you report! We will look into that.
