### ISSUE TITLE
[Bug] 'EditValLoop' object has no attribute 'dataloader'

### ISSUE THREAD

**Issue by angryhen** [open-mmlab/mmediting#1688]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmediting/tree/1.x

### Environment

Cant not found mmedit/utils/collect_env.py

### Reproduces the problem - code sample

```
custom_hooks = [
    dict(
        type='GenVisualizationHook',
        interval=100,
        fixed_input=True,
        vis_kwargs_list=[
            dict(type='Translation', name='trans'),
            dict(type='TranslationVal', name='trans_val')
        ])
]
```

### Reproduces the problem - command or script

 ```python tools/train.py configs/cyclegan/cyclegan_lsgan-resnet-in_1xb1-250kiters_summer2winter.py```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "tools/train.py", line 111, in <module>
    main()
  File "tools/train.py", line 104, in main
    runner.train()
  File "/home/d0108/miniconda3/envs/mmedit/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1686, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/d0108/miniconda3/envs/mmedit/lib/python3.8/site-packages/mmengine/runner/loops.py", line 264, in run
    self.run_iter(data_batch)
  File "/home/d0108/miniconda3/envs/mmedit/lib/python3.8/site-packages/mmengine/runner/loops.py", line 290, in run_iter
    self.runner.call_hook(
  File "/home/d0108/miniconda3/envs/mmedit/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1748, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "/home/d0108/miniconda3/envs/mmedit/lib/python3.8/site-packages/mmengine/dist/utils.py", line 360, in wrapper
    return func(*args, **kwargs)
  File "/home/d0108/project/github/mmediting/mmedit/engine/hooks/visualization_hook.py", line 291, in after_train_iter
    self.vis_sample(runner, batch_idx, data_batch, outputs)
  File "/home/d0108/miniconda3/envs/mmedit/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/d0108/project/github/mmediting/mmedit/engine/hooks/visualization_hook.py", line 352, in vis_sample
    sampler = get_sampler(vis_kwargs_, runner)
  File "/home/d0108/project/github/mmediting/mmedit/utils/sampler.py", line 30, in get_sampler
    sampler = eval(f'{sampler_type}Sampler')(sampler_kwargs_, runner)
  File "/home/d0108/project/github/mmediting/mmedit/utils/sampler.py", line 137, in __init__
    dataset = runner.val_dataloader.dataset
  File "/home/d0108/miniconda3/envs/mmedit/lib/python3.8/site-packages/mmengine/runner/runner.py", line 589, in val_dataloader
    return self.val_loop.dataloader
AttributeError: 'EditValLoop' object has no attribute 'dataloader'
```

### Additional information

I just run summer2winter and change nothing

**Comment by LeoXing1996** [comment]
Hey @angryhen, thanks for your interest. 
What's your MMEngine and MMEditing version? I tried MMEditing-1.x (71af274a), and validation can run smoothly.

**Comment by angryhen** [comment]
> 嘿@angryhen， 感谢您的关注。 您的 MMEngine 和 MMEditing 是什么版本？我尝试了 MMEditing-1.x ( [71af274](https://github.com/open-mmlab/mmediting/commit/71af274adde5b9308a441c474dfc536cda8256fa) )，验证可以顺利运行。

```
Package                 Version   Editable project location
----------------------- --------- ------------------------------------
absl-py                 1.4.0
addict                  2.4.0
av                      10.0.0
brotlipy                0.7.0
cachetools              5.3.0
certifi                 2022.12.7
cffi                    1.15.1
charset-normalizer      2.0.4
click                   8.1.3
clip                    0.2.0
colorama                0.4.6
coloredlogs             15.0.1
contourpy               1.0.7
cryptography            39.0.1
cycler                  0.11.0
einops                  0.6.0
face-alignment          1.3.5
facexlib                0.2.5
filterpy                1.4.5
flatbuffers             23.3.3
flit_core               3.6.0
fonttools               4.38.0
google-auth             2.16.2
google-auth-oauthlib    0.4.6
grpcio                  1.51.3
humanfriendly           10.0
idna                    3.4
imageio                 2.26.0
importlib-metadata      6.0.0
importlib-resources     5.12.0
kiwisolver              1.4.4
lazy_loader             0.1
llvmlite                0.39.1
lmdb                    1.4.0
lpips                   0.1.4
Markdown                3.4.1
markdown-it-py          2.2.0
MarkupSafe              2.1.2
matplotlib              3.7.1
mdurl                   0.1.2
mkl-fft                 1.3.1
mkl-random              1.2.2
mkl-service             2.4.0
mmcv                    2.0.0rc4
mmedit                  1.0.0rc6  /home/d0108/project/github/mmediting
mmengine                0.6.0
model-index             0.1.11
mpmath                  1.2.1
networkx                3.0
numba                   0.56.4
numpy                   1.23.5
oauthlib                3.2.2
onnxruntime             1.14.1
opencv-python           4.7.0.72
openmim                 0.3.6
ordered-set             4.1.0
packaging               23.0
pandas                  1.5.3
Pillow                  9.4.0
pip                     22.3.1
protobuf                4.22.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycparser               2.21
Pygments                2.14.0
pyOpenSSL               23.0.0
pyparsing               3.0.9
PySocks                 1.7.1
python-dateutil         2.8.2
pytz                    2022.7.1
PyWavelets              1.4.1
PyYAML                  6.0
requests                2.28.1
requests-oauthlib       1.3.1
resize-right            0.0.2
rich                    13.3.2
rsa                     4.9
scikit-image            0.20.0
scipy                   1.9.1
setuptools              65.6.3
six                     1.16.0
sympy                   1.11.1
tabulate                0.9.0
tensorboard             2.12.0
tensorboard-data-server 0.7.0
tensorboard-plugin-wit  1.8.1
termcolor               2.2.0
tifffile                2023.2.28
torch                   1.12.1
torchaudio              0.12.1
torchvision             0.13.1
tqdm                    4.65.0
typing_extensions       4.4.0
urllib3                 1.26.14
v                       3.4.0
Werkzeug                2.2.3
wheel                   0.38.4
yapf                    0.32.0
zipp                    3.15.0
```

**Comment by LeoXing1996** [comment]
@angryhen, can you try PR #1691?

**Comment by LeoXing1996** [comment]
Close this issue since PR #1691 has been merged. Please feel free to re-open if you still face this problem.
