### ISSUE TITLE
NotImplementedError: You must implement the backward function for custom autograd.Function.

### ISSUE THREAD

**Issue by zhangluustb** [open-mmlab/mmediting#175]
`./tools/dist_train.sh configs/mattors/dim/dim_stage1_v16_1x1_1000k_comp1k.py 2`
python3.7

Traceback (most recent call last):
  File "/export/0924_mmediting/mmediting/tools/train.py", line 145, in <module>
    main()
  File "/export/0924_mmediting/mmediting/tools/train.py", line 141, in main
    meta=meta)
  File "/export/0924_mmediting/mmediting/mmedit/apis/train.py", line 78, in train_model
    meta=meta)
  File "/export/0924_mmediting/mmediting/mmedit/apis/train.py", line 294, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/zhanglu/miniconda3/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/zhanglu/miniconda3/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/zhanglu/miniconda3/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/export/0924_mmediting/mmediting/mmedit/models/mattors/base_mattor.py", line 234, in train_step
    loss.backward()
  File "/home/zhanglu/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/zhanglu/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/zhanglu/miniconda3/lib/python3.7/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/home/zhanglu/miniconda3/lib/python3.7/site-packages/torch/autograd/function.py", line 201, in backward
    raise NotImplementedError("You must implement the backward function for custom"
NotImplementedError: You must implement the backward function for custom autograd.Function.

**Comment by zhangluustb** [comment]
@jiaoml1996 @nbei @EndlessSora Could you help me to slove this bug?

**Comment by zhangluustb** [comment]
定位到了问题位置，plain_decoder.py  line 105 将MaxUnpool2d换成nn.MaxUnpool2d即可

**Comment by innerlee** [comment]
@drcut Please check the implementation of MaxUnpool2d
