### ISSUE TITLE
[ Problem using inpainting pretrained models KeyError: 'gt_img_path' ] 

### ISSUE THREAD

**Issue by raoufkeskes** [open-mmlab/mmediting#176]
Hello 

I've been following the instructions of the documentation carefully but at the end when typing 

```
python demo/matting_demo.py configs/inpainting/global_local/gl_256x256_8x12_celeba.py ../gl_256x256_8x12_celeba_20200619-5af0493f.pth tests/data/image/celeba_test.png tests/data/image/bbox_mask.png tests/data/pred/inpainting_celeba.png --imshow --device 0
```
I have the following error 

```
Traceback (most recent call last):
  File "demo/matting_demo.py", line 38, in <module>
    main()
  File "demo/matting_demo.py", line 29, in main
    pred_alpha = matting_inference(model, args.img_path,
  File "/home/raoufks/Downloads/mmediting/mmedit/apis/matting_inference.py", line 69, in matting_inference
    data = test_pipeline(data)
  File "/home/raoufks/Downloads/mmediting/mmedit/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/raoufks/Downloads/mmediting/mmedit/datasets/pipelines/loading.py", line 54, in __call__
    filepath = str(results[f'{self.key}_path'])

KeyError: 'gt_img_path''
```

**Comment by raoufkeskes** [comment]
Copy paste error  ...  inpainting_demo.py instead of matting_demo.py
