### ISSUE TITLE
['AsymmetricAutoencoderKL is already registered in model at mmagic.models.archs'] 

### ISSUE THREAD

**Issue by Maxibugg** [open-mmlab/mmediting#2133]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

when i try  "python mmagic/utils/collect_env.py", 
I have the following issue :

(mmagic) INPIXALDOM\legoffp@INPIXALSTA69:~/Documents/Stage_Pierre/StageP/mmagic> python mmagic/utils/collect_env.py

Traceback (most recent call last):

  File "mmagic/utils/collect_env.py", line 2, in <module>
    from mmcv.utils import collect_env as collect_base_env

  File "/home/INPIXALDOM/legoffp/anaconda3/envs/mmagic/lib/python3.8/site-packages/mmcv/__init__.py", line 3, in <module>
    from .arraymisc import *
  
File "/home/INPIXALDOM/legoffp/anaconda3/envs/mmagic/lib/python3.8/site-packages/mmcv/arraymisc/__init__.py", line 2, in <module>
    from .quantization import dequantize, quantize
 
 File "/home/INPIXALDOM/legoffp/anaconda3/envs/mmagic/lib/python3.8/site-packages/mmcv/arraymisc/quantization.py", line 2, in <module>
    from typing import Union
 
 File "/home/INPIXALDOM/legoffp/Documents/Stage_Pierre/StageP/mmagic/mmagic/utils/typing.py", line 2, in <module>
    from typing import Callable, Dict, List, Sequence, Tuple, Union

ImportError: cannot import name 'Callable' from partially initialized module 'typing' (most likely due to a circular import) (/home/INPIXALDOM/legoffp/Documents/Stage_Pierre/StageP/mmagic/mmagic/utils/typing.py)

### Reproduces the problem - code sample

from mmagic.apis import MMagicInferencer

# Create a MMagicInferencer instance
editor = MMagicInferencer('pix2pix')
# Infer a image. Input image path and output image path is needed.
results = editor.infer(img='../resources/input/translation/gt_mask_0.png', result_out_dir='../resources/output/translation/tutorial_translation_pix2pix_res.jpg')

### Reproduces the problem - command or script

Inside the cell 15 from mmagic_inference_tutorial.ipynb

from mmagic.apis import MMagicInferencer

# Create a MMagicInferencer instance
editor = MMagicInferencer('pix2pix')

# Infer a image. Input image path and output image path is needed.
results = editor.infer(img='../resources/input/translation/gt_mask_0.png', result_out_dir='../resources/output/translation/tutorial_translation_pix2pix_res.jpg')

### Reproduces the problem - error message

![image](https://github.com/open-mmlab/mmagic/assets/98988026/3e300dac-b9c7-4039-bea9-0be9803b9366)
![image](https://github.com/open-mmlab/mmagic/assets/98988026/eb3eda1e-ad5f-4244-abc4-cd6c53068952)
![image](https://github.com/open-mmlab/mmagic/assets/98988026/acda49c2-5834-4001-8af6-3c9d6a8afe78)
![image](https://github.com/open-mmlab/mmagic/assets/98988026/8c9f6d03-6685-4e1e-ba11-2ff7118b48ce)

### Additional information

Here is my major headache when i run the cell 15 from demo/mmagic_inference_tutorial.ipynb
Have anyone meet this problem ? If yes, what was your solution ?
I'm under Linux with conda envirronnement

**Comment by ZhangruiLee** [comment]
I also encountered the same problem

**Comment by chagasantena** [comment]
I also encountered the same problem

Any suggestion?

thanks.
