### ISSUE TITLE
文生图Demo执行后output图片生成不出来[Bug] 

### ISSUE THREAD

**Issue by learner-dhx** [open-mmlab/mmediting#2137]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

python mmagic/utils/collect_env.py
Traceback (most recent call last):
  File "mmagic/utils/collect_env.py", line 2, in <module>
    from mmcv.utils import collect_env as collect_base_env
  File "D:\python\lib\site-packages\mmcv\__init__.py", line 3, in <module>
    from .arraymisc import *
  File "D:\python\lib\site-packages\mmcv\arraymisc\__init__.py", line 2, in <module>
    from .quantization import dequantize, quantize
  File "D:\python\lib\site-packages\mmcv\arraymisc\quantization.py", line 2, in <module>
    from typing import Union
  File "E:\exploreMmagic\mmagic\mmagic\utils\typing.py", line 2, in <module>
    from typing import Callable, Dict, List, Sequence, Tuple, Union
ImportError: cannot import name 'Callable' from partially initialized module 'typing' (most likely due to a circular import) (E:\exploreMmagic\mmagic\mmagic\utils\typing.py)

### Reproduces the problem - code sample

from mmagic.apis import MMagicInferencer
sd_inferencer = MMagicInferencer(model_name='stable_diffusion')
text_prompts = 'A panda is having dinner at KFC'
result_out_dir = './output/sd_res.png'
sd_inferencer.infer(text=text_prompts, result_out_dir=result_out_dir)

### Reproduces the problem - command or script

from mmagic.apis import MMagicInferencer
sd_inferencer = MMagicInferencer(model_name='stable_diffusion')
text_prompts = 'A panda is having dinner at KFC'
result_out_dir = './output/sd_res.png'
sd_inferencer.infer(text=text_prompts, result_out_dir=result_out_dir)

### Reproduces the problem - error message

prompt no error
![image](https://github.com/open-mmlab/mmagic/assets/97203786/2eb9e50e-88b3-4a67-92f4-649c79ae5573)

**Comment by learner-dhx** [comment]
I need help seriously
