### ISSUE TITLE
[Bug] MMCV-Full required but failed installation

### ISSUE THREAD

**Issue by OtenMoten** [open-mmlab/mmediting#2148]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

[computer_info.json](https://github.com/user-attachments/files/16194471/computer_info.json)
 
PyCharm 2024.1.1 (Professional Edition) 
Build #PY-241.15989.155, built on April 29, 2024

Runtime version: 17.0.10+1-b1207.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

### Reproduces the problem - code sample

` mim install mmcv-full>=1.7.2`

### Reproduces the problem - command or script

` mim install mmcv-full>=1.7.2`

### Reproduces the problem - error message

[error.txt](https://github.com/user-attachments/files/16194491/error.txt)

**Comment by OtenMoten** [comment]
I've deinstalled `mmcv` and installed `mmcv-full 1.7.2` and now this error appears: 

```
C:\Users\Kevin\Documents\PyCharmProjects\tools\mmagic\.venv\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Kevin\Documents\PyCharmProjects\tools\mmagic\main.py", line 1, in <module>
    import mmagic
  File "C:\Users\Kevin\Documents\PyCharmProjects\tools\mmagic\.venv\lib\site-packages\mmagic\__init__.py", line 35, in <module>
    assert (mmcv_min_version <= mmcv_version < mmcv_max_version), \
AssertionError: mmcv==1.7.2 is used but incompatible. Please install mmcv-full>=(2, 0, 0, 0, 0, 0), <(2, 2, 0, 0, 0, 0).
```

in this code: 

```
import mmagic


def main():

    print(mmagic.__version__)


if __name__ == '__main__':

    main()

```

**Comment by impaktor** [comment]
I'm getting the same error. 
It seems it depends on mmcv-full > 2.0.0, but there's no such version? Seems like 1.7.2 is the highest version my package manager can find.

I'm following the README install instructions, I've also followed the instructions in the [docs](https://mmagic.readthedocs.io/en/latest/get_started/install.html), I've tried using both the `mim` installer, as well as poetry.

At the time of writing, latest commit is 9 months ago, and open issues seem to go unanswered.

Related: #1968 #2146 #1821 

Update: I've also tried building the [docker image](https://github.com/open-mmlab/mmagic/tree/main/docker) but that fails (`AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'`), nor does using the requirements.txt file in the repo solve the issue.

**Comment by rlewkowicz** [comment]
I'm spamming this. I think all these issues are the same. It looks like this halted a year ago almost. 
https://github.com/open-mmlab/mmagic/compare/main...rlewkowicz:mmagic:main

This dockerfile will make you a functioning tool chain and your mileage may vary, but I have issues with all the deblur and video enhancements. I wanna like this kinda projects, but they never work. This, paddle paddle. It's all great but terrible ops. It's easier to go papers with code and just hack up a small write then try to use these all in ones.
