### ISSUE TITLE
Can't run demo/restoration_demo.py in docker

### ISSUE THREAD

**Issue by P-Light** [open-mmlab/mmediting#230]
Hello! Tried execute restoration_demo.py and got error:
```bash
Traceback (most recent call last):
  File "demo/restoration_demo.py", line 3, in <module>
    import mmcv
  File "/opt/conda/lib/python3.7/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/opt/conda/lib/python3.7/site-packages/mmcv/fileio/__init__.py", line 4, in <module>
    from .io import dump, load, register_handler
  File "/opt/conda/lib/python3.7/site-packages/mmcv/fileio/io.py", line 4, in <module>
    from ..utils import is_list_of, is_str
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/__init__.py", line 34, in <module>
    from .env import collect_env
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/env.py", line 8, in <module>
    import cv2
  File "/opt/conda/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```
After installing libgl1-mesa-glx by apt got new error:

```bash
Traceback (most recent call last):
  File "demo/restoration_demo.py", line 6, in <module>
    from mmedit.apis import init_model, restoration_inference
  File "/mmediting/mmedit/__init__.py", line 27, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.3.0 is used but incompatible. Please install mmcv>=[1, 0, 2], <=[1, 3].
```

**Comment by P-Light** [comment]
Need to update Dockerfile.

**Comment by innerlee** [comment]
Thanks for the report, we will fix this soon

**Comment by castim** [comment]
Hi! I am encountering the same error, is there an easy fix?

**Comment by Yshuo-Li** [comment]
We have updated the `dockerfile` in #501 .

**Comment by P-Light** [comment]
Looks good, but I can't test it now. I'll close issue, anyway everybody feel free re-open issue.
