### ISSUE TITLE
KeyError: 'gt_path'

### ISSUE THREAD

**Issue by deltabravozulu** [open-mmlab/mmediting#267]
For some reason, if I run the restoration demo using edsr, it breaks. This happens to others. I can at least ameliorate the issue if I go in and change mmediting/mmedit/apis/restoration_inference in this way:
`keys_to_remove = ['gt']` --> `keys_to_remove = ['gt','gt_path']` but I don't know enough about this to know if I'm breaking stuff or not. 

```
$ python demo/restoration_demo.py configs/restorers/edsr/edsr_x2c64b16_g1_300k_div2k.py edsr_x2c64b16_1x16_300k_div2k_20200604-19fe95ea.pth testimage.jpeg testimage_edsr.jpeg
Use load_from_local loader
Traceback (most recent call last):
  File "demo/restoration_demo.py", line 38, in <module>
    main()
  File "demo/restoration_demo.py", line 29, in main
    output = restoration_inference(model, args.img_path)
  File "/home/user/github/mmediting/mmedit/apis/restoration_inference.py", line 35, in restoration_inference
    data = test_pipeline(data)
  File "/home/user/github/mmediting/mmedit/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/user/github/mmediting/mmedit/datasets/pipelines/formating.py", line 254, in __call__
    img_meta[key] = results[key]
KeyError: 'gt_path'
```

**Comment by Yshuo-Li** [comment]
Thanks for your contribution, the issue has been solved in #270.
