### ISSUE TITLE
RuntimeError: transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by ShaofengZou** [open-mmlab/mmediting#344]
Hey, 

I got touble of this runtimerror when using RTX2080ti with CUDA10.1. I have try a lot of methods to fix this problem but end up not working.

Here is my device information:
```
2021-05-31 10:31:51,427 - mmedit - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.6.13 (default, Feb 20 2021, 21:42:50) [GCC 5.4.0 20160609]
CUDA available: True
GPU 0,1,2,3,4,5,6: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GCC: gcc (Ubuntu 6.5.0-2ubuntu1~16.04) 6.5.0 20181026
PyTorch: 1.7.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.0
OpenCV: 4.4.0
MMCV: 1.3.4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMEditing: 0.7.0+fccaebc
------------------------------------------------------------
```

Here is the log of error:
```
2021-05-31 10:26:14,711 - mmedit - INFO - workflow: [('train', 1)], max: 500000 iters
Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 149, in main
    meta=meta)

....

  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f8cb87b78b2 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f8cb8a09952 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f8cb87a2b7d in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x5feada (0x7f8d02f9fada in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x5feb86 (0x7f8d02f9fb86 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #5: /usr/bin/python() [0x536bec]
frame #6: /usr/bin/python() [0x517b07]
frame #7: /usr/bin/python() [0x52df8a]
frame #8: /usr/bin/python() [0x52df8a]
frame #9: /usr/bin/python() [0x4fa207]
frame #10: /usr/bin/python() [0x4dd197]
frame #11: /usr/bin/python() [0x4dd1ad]
frame #12: /usr/bin/python() [0x4dd1ad]
frame #13: /usr/bin/python() [0x4dd1ad]
frame #14: /usr/bin/python() [0x4dd1ad]
frame #15: /usr/bin/python() [0x4dd1ad]
frame #16: /usr/bin/python() [0x4dd1ad]
frame #17: /usr/bin/python() [0x601a43]
frame #18: PyDict_SetItemString + 0x71 (0x515591 in /usr/bin/python)
frame #19: PyImport_Cleanup + 0x83 (0x594053 in /usr/bin/python)
frame #20: Py_FinalizeEx + 0x5c (0x5e9a4c in /usr/bin/python)
frame #21: Py_Main + 0x392 (0x5efd42 in /usr/bin/python)
frame #22: main + 0xe9 (0x4d2159 in /usr/bin/python)
frame #23: __libc_start_main + 0xf0 (0x7f8d0c837830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #24: _start + 0x29 (0x5e8289 in /usr/bin/python)
```

**Comment by innerlee** [comment]
Please provide the full command to reproduce this error

**Comment by ShaofengZou** [comment]
It seems wried.
I have 8 GPUs. No error occurs when I use 4 cards from 0-3. But when I use the last 4 cards, it will go wrong.

**Comment by innerlee** [comment]
Are the cards specified by CUDA_VISIBLE_DEVICES?

**Comment by ShaofengZou** [comment]
yes!

When I use 4 cards from 0-3, i use command like:
> bash tools/dist_train.sh configs/xxxx.py 4

When I use the last 4 cards from 4-7, i use command like:
> CUDA_VISIBLE_DEVICES=4,5,6,7 bash tools/dist_train.sh configs/xxxx.py 4

**Comment by innerlee** [comment]
Which config is used? If the config is private, then can you reproduce the error with public configs?

**Comment by ShaofengZou** [comment]
Yes, I use private configuration on this machine with 8 RTX2080ti GPUs. I tried some public configurations, but no errors occurred.

I have another machine with 8 Titanxp GPUs, no matter which cards I use, there will be no errors with my private config.

I think there may be no problem with my config. It may be the hardware environment or the drivers of CUDA and NVIDIA may need to be updated.

**Comment by innerlee** [comment]
Yeah its hard to debug, in this case

**Comment by ShaofengZou** [comment]
Thanks for your help anyway! :beer::beers:

**Comment by innerlee** [comment]
A shotin the dark. If you have syncbn, then replace it by normal bn

**Comment by ShaofengZou** [comment]
Cool ~ I will try it !
