### ISSUE TITLE
Please help me with use vid4 and vimo90k

### ISSUE THREAD

**Issue by luoyinTT** [open-mmlab/mmediting#346]
(1)What is the file structure of vimo90k, 
(2)when i use vid4 for basicvsr to test , i always meet : 

Original Traceback (most recent call last):
```bash
  File "/scratch/workspace/yinl/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/scratch/workspace/yinl/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch/workspace/yinl/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/group/dphi_algo_scratch_03/yinl/mmediting-master/mmedit/datasets/base_sr_dataset.py", line 52, in __getitem__
    return self.pipeline(results)
  File "/group/dphi_algo_scratch_03/yinl/mmediting-master/mmedit/datasets/pipelines/compose.py", line 43, in __call__
    data = t(data)
  File "/group/dphi_algo_scratch_03/yinl/mmediting-master/mmedit/datasets/pipelines/loading.py", line 135, in __call__
    f'filepath should be list, but got {type(filepaths)}')
TypeError: filepath should be list, but got <class 'str'>
```

in the config file:

```python
test_dataset_type = 'SRVid4Dataset'
# test
    test=dict(
        type=test_dataset_type,
        lq_folder='videoSR/BIx4',
        gt_folder='videoSR/original',
        ann_file='videoSR/annotation.txt',
        pipeline=test_pipeline,
        scale=4,
        filename_tmpl='{:03d}',
        num_input_frames=7,
        test_mode=True),
)
```

**Comment by ckkelvinchan** [comment]
1. Vimeo-90K has a structure of `clip/sequence/img.png`. For instance, 
```
| 00001
    | 0001
        | im1.png
        | im2.png
             ...
    | 0002
      ...
| 00002
   ...
```

2. `SRVid4Dataset` is for sliding-window methods such as `EDVR`. Please use `SRTestMultipleGTDataset`. For more details, please refer to the validation settings in [basicvsr_vimeo90k_bd.py](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/basicvsr/basicvsr_vimeo90k_bd.py#L19).

**Comment by innerlee** [comment]
@ckkelvinchan please add folder structure in the doc https://mmediting.readthedocs.io/en/latest/sr_datasets.html#vimeo90k-dataset

**Comment by luoyinTT** [comment]
@ckkelvinchan 
i change config file:

test_dataset_type = 'SRTestMultipleGTDataset'

test_pipeline = [
    dict(
        type='LoadImageFromFileList',
        io_backend='disk',
        key='lq',
        channel_order='rgb'),
    dict(
        type='LoadImageFromFileList',
        io_backend='disk',
        key='gt',
        channel_order='rgb'),
    dict(type='RescaleToZeroOne', keys=['lq', 'gt']),
    dict(type='MirrorSequence', keys=['lq']),
    dict(type='FramesToTensor', keys=['lq', 'gt']),
    dict(
        type='Collect',
        keys=['lq', 'gt'],
        meta_keys=['lq_path', 'gt_path', 'key'])
]

test=dict(
        type=test_dataset_type,
        lq_folder='videoSR/BIx4',
        gt_folder='videoSR/original',
        pipeline=test_pipeline,
        scale=4,
        test_mode=True),
)
the same as SRTestMultipleGTDataset

- my vid4 dataset structure is 

| videoSR 
     | BIx4
          | city
             | Frame001.jpg
             ...
          ...
     | original
          | city
             | Frame001.jpg
             ...        
          ...

**but i still meet the problem:**

Traceback (most recent call last):
  File "tools/test.py", line 136, in <module>
    main()
  File "tools/test.py", line 99, in main
    save_image=args.save_image)
  File "/group/dphi_algo_scratch_03/yinl/mmediting-master/mmedit/apis/test.py", line 40, in single_gpu_test
    for data in data_loader:
  File "/scratch/workspace/yinl/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/scratch/workspace/yinl/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/scratch/workspace/yinl/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/scratch/workspace/yinl/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/scratch/workspace/yinl/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/scratch/workspace/yinl/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch/workspace/yinl/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/group/dphi_algo_scratch_03/yinl/mmediting-master/mmedit/datasets/base_sr_dataset.py", line 52, in __getitem__
    return self.pipeline(results)
  File "/group/dphi_algo_scratch_03/yinl/mmediting-master/mmedit/datasets/pipelines/compose.py", line 43, in __call__
    data = t(data)
  File "/group/dphi_algo_scratch_03/yinl/mmediting-master/mmedit/datasets/pipelines/loading.py", line 135, in __call__
    f'filepath should be list, but got {type(filepaths)}')
TypeError: filepath should be list, but got <class 'str'>

**Comment by ckkelvinchan** [comment]
Your test_pipline is not correct. You should use

```
test_pipeline = [
    dict(type='GenerateSegmentIndices', interval_list=[1], filename_tmpl='Frame{:03d}.jpg', start_index=1),
    dict(
        type='LoadImageFromFileList',
        io_backend='disk',
        key='lq',
        channel_order='rgb'),
    dict(
        type='LoadImageFromFileList',
        io_backend='disk',
        key='gt',
        channel_order='rgb'),
    dict(type='RescaleToZeroOne', keys=['lq', 'gt']),
    dict(type='FramesToTensor', keys=['lq', 'gt']),
    dict(
        type='Collect',
        keys=['lq', 'gt'],
        meta_keys=['lq_path', 'gt_path', 'key'])
]
```
Moreover, please note the use of `filename_tmpl='Frame{:03d}.jpg'` and `start_index=1` in `GenerateSegmentIndices`. Please find more details [here](https://github.com/open-mmlab/mmediting/blob/master/mmedit/datasets/pipelines/augmentation.py).

**Comment by ckkelvinchan** [comment]
> @ckkelvinchan please add folder structure in the doc https://mmediting.readthedocs.io/en/latest/sr_datasets.html#vimeo90k-dataset

Okay.

**Comment by luoyinTT** [comment]
@ckkelvinchan 
thank you for your reply, i also want to know  if i use vimo90k, do i have to run the preprocess_vimeo90k_dataset.py ?

and if i use vimeo90k to train basicvsr
the train_pipline and data train is right like this ?

mmedit/models/restorers/basic_restorer.py


train_pipeline = [    dict(        type='LoadImageFromFileList',        io_backend='disk',        key='lq',        channel_order='rgb'),    dict(        type='LoadImageFromFileList',        io_backend='disk',        key='gt',        channel_order='rgb'),    dict(type='RescaleToZeroOne', keys=['lq', 'gt']),    dict(type='PairedRandomCrop', gt_patch_size=256),    dict(        type='Flip', keys=['lq', 'gt'], flip_ratio=0.5,        direction='horizontal'),    dict(type='Flip', keys=['lq', 'gt'], flip_ratio=0.5, direction='vertical'),    dict(type='RandomTransposeHW', keys=['lq', 'gt'], transpose_ratio=0.5),    dict(type='MirrorSequence', keys=['lq', 'gt']),    dict(type='FramesToTensor', keys=['lq', 'gt']),    dict(type='Collect', keys=['lq', 'gt'], meta_keys=['lq_path', 'gt_path'])]



# train    train=dict(        type='RepeatDataset',        times=1000,        dataset=dict(            type=train_dataset_type,            lq_folder='data/vimeo90k/BIx4',            gt_folder='data/vimeo90k/GT',            ann_file='data/vimeo90k/meta_info_Vimeo90K_train_GT.txt',            pipeline=train_pipeline,            scale=4,            test_mode=False)),

**Comment by ckkelvinchan** [comment]
Yes, you can use `preprocess_vimeo90k_dataset.py` to generate the annotation file.

And you can follow exactly [basicvsr_vimeo90k_bi.py](https://github.com/hahnjiang/mmediting/blob/master/configs/restorers/basicvsr/basicvsr_vimeo90k_bi.py) for training on Vimeo-90K.

**Comment by luoyinTT** [comment]
@ckkelvinchan thank you ^^

**Comment by ckkelvinchan** [comment]
Closing due to inactivity, please reopen if there are any further problems.
