### ISSUE TITLE
super-resolution train(liif) problem

### ISSUE THREAD

**Issue by kimtaehyeong** [open-mmlab/mmediting#364]
hello, Thanks for the work.
I want to train a 'liif' model on my data.
To learn the open dataset (div2k) before custom learning, I visited 'https://mmediting.readthedocs.io/en/latest/sr_datasets.html#div2k-dataset' and created the data as the following structure.

```text
mmediting
├── mmedit
├── tools
├── configs
├── data
│   ├── DIV2K
│   │   ├── DIV2K_train_HR
│   │   ├── DIV2K_train_LR_bicubic
│   │   │   ├── X2
│   │   │   ├── X3
│   │   │   ├── X4
│   │   ├── DIV2K_valid_HR
│   │   ├── DIV2K_valid_LR_bicubic
│   │   │   ├── X2
│   │   │   ├── X3
│   │   │   ├── X4
│   ├── val_set5
│   │   ├── Set5_bicLRx2
│   │   ├── Set5_bicLRx3
│   │   ├── Set5_bicLRx4
│   ├── val_set14
│   │   ├── Set14_bicLRx2
│   │   ├── Set14_bicLRx3
│   │   ├── Set14_bicLRx4
```

Then, after entering the following command, I wanted to learn.
'./tools/dist_train.sh configs/restorers/liif/liif_edsr_norm_x2-4_c64b16_g1_1000k_div2k.py 1'

But I got the following error:

```bash
Traceback (most recent call last):
  File "/home/anaconda3/envs/open_mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/project/mmediting/mmedit/datasets/sr_folder_gt_dataset.py", line 46, in __init__
    super().__init__(pipeline, scale, test_mode)
  File "/home/project/mmediting/mmedit/datasets/base_sr_dataset.py", line 19, in __init__
    super().__init__(pipeline, test_mode)
  File "/home/project/mmediting/mmedit/datasets/base_dataset.py", line 27, in __init__
    self.pipeline = Compose(pipeline)
  File "/home/project/mmediting/mmedit/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/home/anaconda3/envs/open_mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: RandomDownSampling: __init__() got an unexpected keyword argument 'inp_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/train.py", line 145, in <module>
    main()
  File "./tools/train.py", line 111, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/project/mmediting/mmedit/datasets/builder.py", line 76, in build_dataset
    build_dataset(cfg['dataset'], default_args), cfg['times'])
  File "/home/project/mmediting/mmedit/datasets/builder.py", line 80, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/anaconda3/envs/open_mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SRFolderGTDataset: RandomDownSampling: __init__() got an unexpected keyword argument 'inp_size'
Traceback (most recent call last):
  File "/home/anaconda3/envs/open_mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/envs/open_mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/open_mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/anaconda3/envs/open_mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/anaconda3/envs/open_mmlab/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/restorers/liif/liif_edsr_norm_x2-4_c64b16_g1_1000k_div2k.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

```

Is there any way to fix this error?

Also, can you write a tutorial for training my data?

Thank you so much.

**Comment by kimtaehyeong** [comment]
The environment I used is ubuntu 18.04 / anaconda / Quadro RTX 6000 1 / pytorch 1.6.

thank you.

**Comment by Yshuo-Li** [comment]
Some parameters of the config file failed to match with the pipeline, we have fixed this issue in #368 .

**Comment by Yshuo-Li** [comment]
Now you can use `./tools/dist_train.sh configs/restorers/liif/liif_edsr_norm_x2-4_c64b16_g1_1000k_div2k.py 1` to train your data.

**Comment by kimtaehyeong** [comment]
thank you!
