### ISSUE TITLE
Some problems about edvrm

### ISSUE THREAD

**Issue by Shuweis** [open-mmlab/mmediting#477]
When I train the edvrm_wotsa_x4_g8_600k_reds, in validation period it raise the KeyError.

Traceback (most recent call last):
  File "./tools/train.py", line 145, in <module>
    main()
  File "./tools/train.py", line 141, in main
    meta=meta)
  File "/home/swshi/mmediting/mmedit/apis/train.py", line 71, in train_model
    meta=meta)
  File "/home/swshi/mmediting/mmedit/apis/train.py", line 204, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/swshi/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/swshi/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/home/swshi/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/swshi/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/logger/base.py", line 152, in after_train_iter
    self.log(runner)
  File "/home/swshi/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/logger/text.py", line 177, in log
    self._log_info(log_dict, runner)
  File "/home/swshi/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/logger/text.py", line 96, in _log_info
    log_str += f'time: {log_dict["time"]:.3f}, ' \
KeyError: 'data_time'

I do not know what happened. Hope for your reply!

**Comment by ckkelvinchan** [comment]
#473 has a similar problem, could you see if it helps?

**Comment by Shuweis** [comment]
Yes, the error was solved.Thank you!
