### ISSUE TITLE
Some problems occur when I train basicvsr every 5000 iterations

### ISSUE THREAD

**Issue by Shuweis** [open-mmlab/mmediting#508]
some errors cause the program interrupt：

data = self._get_data()  File "/home/swshi/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1029, in _get_data

  File "/home/swshi/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1029, in _get_data
    raise RuntimeError('Pin memory thread exited unexpectedly')
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: RuntimeErrorPin memory thread exited unexpectedly:
Pin memory thread exited unexpectedly

I cannot find the problem. Hope for your reply！

**Comment by ckkelvinchan** [comment]
It seems the problem of pin_mermory. Could you try setting pin_memory to False [here](https://github.com/open-mmlab/mmediting/blob/23213c839ff2d1907a80d6ea29f13c32a24bb8ef/mmedit/datasets/builder.py#L82)? I will see what happened.

**Comment by Shuweis** [comment]
Okay, I will try that.Is it the version of cuda or torch cause the problem? Some GPUs only support cuda11 and torch>=1.7.

**Comment by ckkelvinchan** [comment]
That could be. I will look into that.

**Comment by ShiinaMitsuki** [comment]
```python
[                                                  ] 0/4, elapsed: 0s, ETA:Exception in thread Thread-2:                                                                                                                                                                                                                                                                                                                [325/1927]
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    idx, data = r
ValueError: not enough values to unpack (expected 2, got 0)

Traceback (most recent call last):
  File "./tools/train.py", line 146, in <module>
    main()
  File "./tools/train.py", line 142, in main
    meta=meta)
  File "/project/mmediting/mmedit/apis/train.py", line 72, in train_model
    meta=meta)
  File "/project/mmediting/mmedit/apis/train.py", line 206, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/project/mmediting/mmedit/core/evaluation/eval_hooks.py", line 104, in after_train_iter
Traceback (most recent call last):
  File "./tools/train.py", line 146, in <module>
    iteration=runner.iter)
  File "/project/mmediting/mmedit/apis/test.py", line 102, in multi_gpu_test
    for data in data_loader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 349, in __iter__
Traceback (most recent call last):
    main()
  File "./tools/train.py", line 146, in <module>
  File "./tools/train.py", line 142, in main
    self._iterator._reset(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 852, in _reset
    meta=meta)
  File "/project/mmediting/mmedit/apis/train.py", line 72, in train_model
    main()
  File "./tools/train.py", line 142, in main
    meta=meta)
  File "/project/mmediting/mmedit/apis/train.py", line 206, in _dist_train
    meta=meta)
  File "/project/mmediting/mmedit/apis/train.py", line 72, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    data = self._get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1029, in _get_data
    meta=meta)
  File "/project/mmediting/mmedit/apis/train.py", line 206, in _dist_train
    iter_runner(iter_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/iter_based_runner.py", line 66, in train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    self.call_hook('after_train_iter')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    iter_runner(iter_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/iter_based_runner.py", line 66, in train
    getattr(hook, fn_name)(self)
  File "/project/mmediting/mmedit/core/evaluation/eval_hooks.py", line 104, in after_train_iter
    self.call_hook('after_train_iter')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    iteration=runner.iter)
    raise RuntimeError('Pin memory thread exited unexpectedly')
  File "/project/mmediting/mmedit/apis/test.py", line 102, in multi_gpu_test
RuntimeError: Pin memory thread exited unexpectedly
    getattr(hook, fn_name)(self)
  File "/project/mmediting/mmedit/core/evaluation/eval_hooks.py", line 104, in after_train_iter
    for data in data_loader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 349, in __iter__
    iteration=runner.iter)
  File "/project/mmediting/mmedit/apis/test.py", line 102, in multi_gpu_test
    for data in data_loader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 349, in __iter__
    self._iterator._reset(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 852, in _reset
    self._iterator._reset(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 852, in _reset
    data = self._get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1029, in _get_data
    data = self._get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1029, in _get_data
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly

```
it seems the same problem,

**Comment by ckkelvinchan** [comment]
> It seems the problem of pin_mermory. Could you try setting pin_memory to False [here](https://github.com/open-mmlab/mmediting/blob/23213c839ff2d1907a80d6ea29f13c32a24bb8ef/mmedit/datasets/builder.py#L82)? I will see what happened.

@ShiinaMitsuki Did you try setting `pin_memory=False` here? I am sorry that I am a bit busy recently, and I will look into the problem asap.

**Comment by ckkelvinchan** [comment]
I found a similar issue [here](https://github.com/pytorch/pytorch/issues/47445). You can try updating PyTorch and see if there is any problem? 

By the way, I have tried it using PyTorch 1.7.1 and there is no problem. You can have a try.

**Comment by ShiinaMitsuki** [comment]
> > It seems the problem of pin_mermory. Could you try setting pin_memory to False [here](https://github.com/open-mmlab/mmediting/blob/23213c839ff2d1907a80d6ea29f13c32a24bb8ef/mmedit/datasets/builder.py#L82)? I will see what happened.
> 
> @ShiinaMitsuki Did you try setting `pin_memory=False` here? I am sorry that I am a bit busy recently, and I will look into the problem asap.

I tried, and the error disappear.
