### ISSUE TITLE
training basicVSR with REDS failed after 5000 iterations

### ISSUE THREAD

**Issue by fujin678** [open-mmlab/mmediting#511]
my command for training:
./tools/dist_train.sh ./configs/restorers/basicvsr/basicvsr_reds4.py 2

my GPU info (it has 12GB memory),

nvidia-smi
Mon Aug 30 14:58:44 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN V      On   | 00000000:3B:00.0 Off |                  N/A |
| 28%   35C    P8    26W / 250W |      4MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA TITAN V      On   | 00000000:D9:00.0 Off |                  N/A |
| 28%   33C    P8    26W / 250W |      4MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                              

Error log:

2021-08-30 14:48:46,543 - mmedit - INFO - Iter [4800/300000]	lr_generator: 2.498e-05, eta: 4 days, 2:40:04, time: 1.206, data_time: 0.006, memory: 10213, loss_pix: 0.0223, loss: 0.0223
2021-08-30 14:50:47,039 - mmedit - INFO - Iter [4900/300000]	lr_generator: 2.498e-05, eta: 4 days, 2:38:14, time: 1.205, data_time: 0.006, memory: 10213, loss_pix: 0.0230, loss: 0.0230
2021-08-30 14:52:47,954 - mmedit - INFO - Saving checkpoint at 5000 iterations
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 4/4, 0.0 task/s, elapsed: 106s, ETA:     0s

2021-08-30 14:54:34,021 - mmedit - INFO - Exp name: basicvsr_reds4
2021-08-30 14:54:34,021 - mmedit - INFO - Iter(val) [5000]	PSNR: 29.6896, SSIM: 0.8517
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
Traceback (most recent call last):
  File "./tools/train.py", line 146, in <module>
    main()
  File "./tools/train.py", line 142, in main
    meta=meta)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/apis/train.py", line 72, in train_model
    meta=meta)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/apis/train.py", line 206, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/fjin2/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/fjin2/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/core/distributed_wrapper.py", line 126, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/models/restorers/basicvsr.py", line 87, in train_step
    outputs = self(**data_batch, test_mode=False)
  File "/home/fjin2/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fjin2/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/models/restorers/basic_restorer.py", line 77, in forward
    return self.forward_train(lq, gt)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/models/restorers/basic_restorer.py", line 91, in forward_train
    loss_pix = self.pixel_loss(output, gt)
  File "/home/fjin2/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/models/losses/pixelwise_loss.py", line 189, in forward
    sample_wise=self.sample_wise)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/models/losses/utils.py", line 111, in wrapper
    loss = loss_func(pred, target, **kwargs)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/models/losses/pixelwise_loss.py", line 51, in charbonnier_loss
    return torch.sqrt((pred - target)**2 + eps)
RuntimeError: CUDA out of memory. Tried to allocate 46.00 MiB (GPU 1; 11.78 GiB total capacity; 10.27 GiB already allocated; 12.88 MiB free; 10.41 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "./tools/train.py", line 146, in <module>
    main()
  File "./tools/train.py", line 142, in main
    meta=meta)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/apis/train.py", line 72, in train_model
    meta=meta)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/apis/train.py", line 206, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/fjin2/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/fjin2/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/core/distributed_wrapper.py", line 126, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/models/restorers/basicvsr.py", line 87, in train_step
    outputs = self(**data_batch, test_mode=False)
  File "/home/fjin2/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fjin2/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/models/restorers/basic_restorer.py", line 77, in forward
    return self.forward_train(lq, gt)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/models/restorers/basic_restorer.py", line 91, in forward_train
    loss_pix = self.pixel_loss(output, gt)
  File "/home/fjin2/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/models/losses/pixelwise_loss.py", line 189, in forward
    sample_wise=self.sample_wise)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/models/losses/utils.py", line 111, in wrapper
    loss = loss_func(pred, target, **kwargs)
  File "/home/fjin2/workspace/tensorflow/mmediting/mmedit/models/losses/pixelwise_loss.py", line 51, in charbonnier_loss
    return torch.sqrt((pred - target)**2 + eps)
RuntimeError: CUDA out of memory. Tried to allocate 46.00 MiB (GPU 0; 11.78 GiB total capacity; 10.27 GiB already allocated; 12.88 MiB free; 10.41 GiB reserved in total by PyTorch)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2532) of binary: /home/fjin2/miniconda3/envs/open-mmlab/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1]
  role_ranks=[0, 1]
  global_ranks=[0, 1]
  role_world_sizes=[2, 2]
  global_world_sizes=[2, 2]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_nomkno2s/none_8wszj_yq/attempt_1/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_nomkno2s/none_8wszj_yq/attempt_1/1/error.json

**Comment by ckkelvinchan** [comment]
From the error log, I think there is insufficient memory. After 5000 iterations, the optical flow network will be trained with the restoration network, and therefore memory consumption increases. Please try to reduce the batch size or sequence length during training, and see if there is any problem.
