### ISSUE TITLE
TDAN training has error 

### ISSUE THREAD

**Issue by dzz416** [open-mmlab/mmediting#522]
I have GPU titan 1080TI,12G, use the command ：
 CUDA_VISIBLE_DEVICES=2 python tools/train.py configs/restorers/tdan/tdan_vimeo90k_bix4_ft_lr5e-5_400k.py --work-dir output
to train the model on vimeo90K, error occured:

2021-09-07 16:30:00,025 - mmedit - INFO - load checkpoint from tdancheckpoints/tdan_vimeo90k_bix4_20210528-739979d9.pth
2021-09-07 16:30:00,025 - mmedit - INFO - Use load_from_local loader
2021-09-07 16:30:00,039 - mmedit - INFO - Start running, host: dzz@ubuntu, work_dir: /home1/dzzHD/mmediting/output
2021-09-07 16:30:00,040 - mmedit - INFO - workflow: [('train', 1)], max: 400000 iters
/home1/dzzHD/mmediting/mmedit/models/losses/pixelwise_loss.py:37: UserWarning: Using a target size (torch.Size([16, 5, 3, 192, 192])) that is different to the input size (torch.Size([16, 3, 192, 192])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(pred, target, reduction='none')
Traceback (most recent call last):
  File "tools/train.py", line 146, in <module>
    main()
  File "tools/train.py", line 142, in main
    meta=meta)
  File "/home1/dzzHD/mmediting/mmedit/apis/train.py", line 81, in train_model
    meta=meta)
  File "/home1/dzzHD/mmediting/mmedit/apis/train.py", line 330, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/dzz/.local/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 131, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/dzz/.local/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/dzz/.local/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home1/dzzHD/mmediting/mmedit/models/restorers/basic_restorer.py", line 188, in train_step
    outputs = self(**data_batch, test_mode=False)
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dzz/.local/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home1/dzzHD/mmediting/mmedit/models/restorers/basic_restorer.py", line 77, in forward
    return self.forward_train(lq, gt)
  File "/home1/dzzHD/mmediting/mmedit/models/restorers/tdan.py", line 56, in forward_train
    loss_pix = self.pixel_loss(output, gt)
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/dzzHD/mmediting/mmedit/models/losses/pixelwise_loss.py", line 135, in forward
    sample_wise=self.sample_wise)
  File "/home1/dzzHD/mmediting/mmedit/models/losses/utils.py", line 111, in wrapper
    loss = loss_func(pred, target, **kwargs)
  File "/home1/dzzHD/mmediting/mmedit/models/losses/pixelwise_loss.py", line 37, in mse_loss
    return F.mse_loss(pred, target, reduction='none')
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/nn/functional.py", line 2659, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/functional.py", line 71, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore
RuntimeError: The size of tensor a (16) must match the size of tensor b (5) at non-singleton dimension 1

what should i do?

**Comment by ckkelvinchan** [comment]
From the error log it seems that the size of `output` and `gt` do not match. Did you modify the code or config? 

As we have written a [unittest](https://github.com/open-mmlab/mmediting/blob/master/tests/test_models/test_restorers/test_tdan.py#L59) to ensure its correctness. I have also just tried to train on my side and there is no error.

**Comment by dzz416** [comment]
here is the configs file: does it has something wrong? 
exp_name = 'tdan_vimeo90k_bix4_ft_lr5e-5_400k'

# model settings
model = dict(
    type='TDAN',
    generator=dict(type='TDANNet'),
    pixel_loss=dict(type='MSELoss', loss_weight=1.0, reduction='mean'),
    lq_pixel_loss=dict(type='MSELoss', loss_weight=0.25, reduction='mean'))
# model training and testing settings
train_cfg = None
test_cfg = dict(metrics=['PSNR', 'SSIM'], crop_border=8, convert_to='y')

# dataset settings
train_dataset_type = 'SRVimeo90KMultipleGTDataset'
val_dataset_type = 'SRFolderMultipleGTDataset'  ###no need for annofiles
test_dataset_type = 'SRVimeo90KDataset'

train_pipeline = [
    dict(
        type='LoadImageFromFileList',
        io_backend='disk',
        key='lq',
        channel_order='rgb'),
    dict(
        type='LoadImageFromFileList',
        io_backend='disk',
        key='gt',
        channel_order='rgb'),
    dict(type='RescaleToZeroOne', keys=['lq', 'gt']),
    dict(
        type='Normalize',
        keys=['lq', 'gt'],
        mean=[0.5, 0.5, 0.5],
        std=[1, 1, 1]),
    dict(type='PairedRandomCrop', gt_patch_size=192),
    dict(
        type='Flip', keys=['lq', 'gt'], flip_ratio=0.5,
        direction='horizontal'),
    dict(type='Flip', keys=['lq', 'gt'], flip_ratio=0.5, direction='vertical'),
    dict(type='RandomTransposeHW', keys=['lq', 'gt'], transpose_ratio=0.5),
    dict(type='FramesToTensor', keys=['lq', 'gt']),
    dict(type='Collect', keys=['lq', 'gt'], meta_keys=['lq_path', 'gt_path'])
]

val_pipeline = [
    dict(type='GenerateFrameIndiceswithPadding', padding='reflection'),
    dict(
        type='LoadImageFromFileList',
        io_backend='disk',
        key='lq',
        channel_order='rgb'),
    dict(
        type='LoadImageFromFileList',
        io_backend='disk',
        key='gt',
        channel_order='rgb'),
    dict(type='RescaleToZeroOne', keys=['lq', 'gt']),
    dict(
        type='Normalize',
        keys=['lq', 'gt'],
        mean=[0.5, 0.5, 0.5],
        std=[1, 1, 1]),
    dict(type='FramesToTensor', keys=['lq', 'gt']),
    dict(type='Collect', keys=['lq', 'gt'], meta_keys=['lq_path', 'gt_path'])
]

demo_pipeline = [
    dict(type='GenerateSegmentIndices', interval_list=[1]),
    dict(
        type='LoadImageFromFileList',
        io_backend='disk',
        key='lq',
        channel_order='rgb'),
    dict(type='RescaleToZeroOne', keys=['lq']),
    dict(type='Normalize', keys=['lq'], mean=[0.5, 0.5, 0.5], std=[1, 1, 1]),
    dict(type='FramesToTensor', keys=['lq']),
    dict(type='Collect', keys=['lq'], meta_keys=['lq_path', 'key'])
]

data = dict(
    workers_per_gpu=8,
    train_dataloader=dict(samples_per_gpu=16, drop_last=True),  # 8 gpus
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    train=dict(
        type='RepeatDataset',
        times=1000,
        dataset=dict(
            type=train_dataset_type,
            lq_folder='/home1/dzzHD/MIMO-VRN/datasets/Vimeo90Kdata/vimeo_septuplet/LR_x4',
            gt_folder='/home1/dzzHD/MIMO-VRN/datasets/Vimeo90Kdata/vimeo_septuplet/sequences',
            ann_file='/home1/dzzHD/MIMO-VRN/datasets/Vimeo90Kdata/vimeo_septuplet/vimeo_train_GT.txt',
            num_input_frames=5,
            pipeline=train_pipeline,
            scale=4,
            test_mode=False)),
    val=dict(
        type=val_dataset_type,
        lq_folder='/home1/dzzHD/MIMO-VRN/datasets/Vid4data/BIx4',
        gt_folder='/home1/dzzHD/MIMO-VRN/datasets/Vid4data/GT',
        pipeline=val_pipeline,
    #    ann_file='data/Vid4/meta_info_Vid4_GT.txt',
        scale=4,
        num_input_frames=5,
        test_mode=True),
    test=dict(
        type=val_dataset_type,
        lq_folder='/home1/dzzHD/MIMO-VRN/datasets/Vimeo90Kdata/vimeo_septuplet/LR_x4',
        gt_folder='/home1/dzzHD/MIMO-VRN/datasets/Vimeo90Kdata/vimeo_septuplet/sequences',
        ann_file='/home1/dzzHD/MIMO-VRN/datasets/Vimeo90Kdata/vimeo_septuplet/vimeo_test_GT.txt',
        pipeline=val_pipeline,
       # ann_file='data/SPMCS/meta_info_SPMCS_GT.txt',
        scale=4,
        num_input_frames=5,
        test_mode=True),
)

# optimizer
optimizers = dict(generator=dict(type='Adam', lr=5e-5))

# learning policy
total_iters = 400000
lr_config = dict(policy='Step', by_epoch=False, step=[400000], gamma=0.5)

checkpoint_config = dict(interval=50000, save_optimizer=True, by_epoch=False)
# remove gpu_collect=True in non distributed training
evaluation = dict(interval=50000, save_image=False, gpu_collect=True)
log_config = dict(
    interval=100,
    hooks=[
        dict(type='TextLoggerHook', by_epoch=False),
        # dict(type='TensorboardLoggerHook'),
    ])
visual_config = None

# runtime settings
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = f'./work_dirs/{exp_name}'
load_from = 'tdancheckpoints/tdan_vimeo90k_bix4_20210528-739979d9.pth'
resume_from = None
workflow = [('train', 1)]

**Comment by ckkelvinchan** [comment]
`val_dataset_type = 'SRFolderMultipleGTDataset' ###no need for annofiles` is used for the recurrent framework such as BasicVSR and BasicVSR++. 

If you are using the sliding window framework such as TDAN and EDVR, please use the original configuration file. The details of the annotation file can be found [here](https://github.com/open-mmlab/mmediting/blob/master/mmedit/datasets/sr_vid4_dataset.py#L21).

**Comment by dzz416** [comment]
thank you !

**Comment by dzz416** [comment]
I m using the sliding window framework  TDAN,the train and val config is the same as original configuration ,but i want to change the test data  from Vimeo90KDataset to Vid4dataset, I have change the test_dataset_type = 'SRVid4Dataset' :

train_dataset_type = 'SRVimeo90KDataset'
val_dataset_type = 'SRVid4Dataset'
test_dataset_type = 'SRVid4Dataset'

and the data[test]:

    val=dict(
        type=val_dataset_type,
        lq_folder='/home1/dzzHD/MIMO-VRN/datasets/Vid4data/BIx4',
        gt_folder='/home1/dzzHD/MIMO-VRN/datasets/Vid4data/GT',
        pipeline=val_pipeline,
        ann_file='/home1/dzzHD/MIMO-VRN/datasets/Vid4data/valname.txt',
        scale=4,
        num_input_frames=5,
        test_mode=True),
    test=dict(
        type=val_dataset_type,
        lq_folder='/home1/dzzHD/MIMO-VRN/datasets/Vid4data/BIx4',
        gt_folder='/home1/dzzHD/MIMO-VRN/datasets/Vid4data/GT',
        pipeline=val_pipeline,
        ann_file='/home1/dzzHD/MIMO-VRN/datasets/Vid4data/valname.txt',
       # ann_file='data/SPMCS/meta_info_SPMCS_GT.txt',
        scale=4,
        num_input_frames=5,
        test_mode=True),


runing test:


 CUDA_VISIBLE_DEVICES=2 python tools/test.py configs/restorers/tdan/tdan_vimeo90k_bix4_ft_lr5e-5_400k.py tdancheckpoints/tdan_vimeo90k_bix4_20210528-739979d9.pth --out output --save-path output

Use load_from_local loader
[                                                  ] 0/171, elapsed: 0s, 
Traceback (most recent call last):
  File "tools/test.py", line 138, in <module>
    main()
  File "tools/test.py", line 101, in main
    save_image=args.save_image)
  File "/home1/dzzHD/mmediting/mmedit/apis/test.py", line 48, in single_gpu_test
    **data)
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dzz/.local/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dzz/.local/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home1/dzzHD/mmediting/mmedit/models/restorers/basic_restorer.py", line 75, in forward
    return self.forward_test(lq, gt, **kwargs)
  File "/home1/dzzHD/mmediting/mmedit/models/restorers/tdan.py", line 132, in forward_test
    clip_name = meta[0]['key'].split('/')[0]
KeyError: 'key'

**Comment by dzz416** [comment]
After 50000 iterations when saving trained model error occur:

_lq: 0.0000, loss: 0.0008
2021-09-08 19:27:59,253 - mmedit - INFO - Saving checkpoint at 50000 iterations
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 171/171, 3.3 task/s, elapsed: 52s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 146, in <module>
    main()
  File "tools/train.py", line 142, in main
    meta=meta)
  File "/home1/dzzHD/mmediting/mmedit/apis/train.py", line 81, in train_model
    meta=meta)
  File "/home1/dzzHD/mmediting/mmedit/apis/train.py", line 330, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/dzz/.local/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 131, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/dzz/.local/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/home/dzz/.local/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home1/dzzHD/mmediting/mmedit/core/evaluation/eval_hooks.py", line 48, in after_train_iter
    self.evaluate(runner, results)
  File "/home1/dzzHD/mmediting/mmedit/core/evaluation/eval_hooks.py", line 58, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
TypeError: evaluate() got an unexpected keyword argument 'gpu_collect'

**Comment by ckkelvinchan** [comment]
I think you did not use distributed training. In this case, you need to remove`gpu_collect` [here](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/tdan/tdan_vimeo90k_bix4_ft_lr5e-5_400k.py#L124).

**Comment by dzz416** [comment]
then should i change the lr if i only have  a single GPU?

**Comment by ckkelvinchan** [comment]
You can still use [dist_train.sh](https://github.com/open-mmlab/mmediting/blob/master/tools/dist_train.sh) even you have a single GPU. 

I think you can try increasing `samples_per_gpu` if memory allows. In our configuration, we use 16x8=128.
