### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by Ha0Tang** [open-mmlab/mmediting#528]
When I was running the command line `sh ./tools/dist_train.sh configs/restorers/edvr/edvrm_wotsa_x4_g8_600k_reds.py 2`, I got the following error:

```bash
2021-09-10 11:44:24,910 - mmedit - INFO - workflow: [('train', 1)], max: 600000 iters
Traceback (most recent call last):
  File "./tools/train.py", line 146, in <module>
    main()
  File "./tools/train.py", line 142, in main
    meta=meta)
  File "/home/ht1/mmediting21/mmedit/apis/train.py", line 72, in train_model
    meta=meta)
  File "/home/ht1/mmediting21/mmedit/apis/train.py", line 206, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/ht1/mmediting21/mmedit/core/distributed_wrapper.py", line 126, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/ht1/mmediting21/mmedit/models/restorers/edvr.py", line 62, in train_step
    outputs = self(**data_batch, test_mode=False)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/ht1/mmediting21/mmedit/models/restorers/basic_restorer.py", line 77, in forward
    return self.forward_train(lq, gt)
  File "/home/ht1/mmediting21/mmedit/models/restorers/basic_restorer.py", line 90, in forward_train
    output = self.generator(lq)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ht1/mmediting21/mmedit/models/backbones/sr_backbones/edvr_net.py", line 425, in forward
    aligned_feat.append(self.pcd_alignment(neighbor_feats, ref_feats))
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ht1/mmediting21/mmedit/models/backbones/sr_backbones/edvr_net.py", line 171, in forward
    feat = self.dcn_pack[level](neighbor_feats[i - 1], offset)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ht1/mmediting21/mmedit/models/backbones/sr_backbones/edvr_net.py", line 58, in forward
    self.deform_groups)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/mmcv/ops/modulated_deform_conv.py", line 91, in forward
    with_bias=ctx.with_bias)
RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "./tools/train.py", line 146, in <module>
    main()
  File "./tools/train.py", line 142, in main
    meta=meta)
  File "/home/ht1/mmediting21/mmedit/apis/train.py", line 72, in train_model
    meta=meta)
  File "/home/ht1/mmediting21/mmedit/apis/train.py", line 206, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/ht1/mmediting/mmedit/core/distributed_wrapper.py", line 126, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/ht1/mmediting/mmedit/models/restorers/edvr.py", line 62, in train_step
    outputs = self(**data_batch, test_mode=False)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/ht1/mmediting/mmedit/models/restorers/basic_restorer.py", line 77, in forward
    return self.forward_train(lq, gt)
  File "/home/ht1/mmediting/mmedit/models/restorers/basic_restorer.py", line 90, in forward_train
    output = self.generator(lq)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ht1/mmediting/mmedit/models/backbones/sr_backbones/edvr_net.py", line 425, in forward
    aligned_feat.append(self.pcd_alignment(neighbor_feats, ref_feats))
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ht1/mmediting/mmedit/models/backbones/sr_backbones/edvr_net.py", line 171, in forward
    feat = self.dcn_pack[level](neighbor_feats[i - 1], offset)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ht1/mmediting/mmedit/models/backbones/sr_backbones/edvr_net.py", line 58, in forward
    self.deform_groups)
  File "/home/ht1/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/mmcv/ops/modulated_deform_conv.py", line 91, in forward
    with_bias=ctx.with_bias)
RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 58060) of binary: /home/ht1/anaconda3/envs/open-mmlab1/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29502
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1]
  role_ranks=[0, 1]
  global_ranks=[0, 1]
  role_world_sizes=[2, 2]
  global_world_sizes=[2, 2]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_i3ew8yeu/none_t71z5tz5/attempt_1/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_i3ew8yeu/none_t71z5tz5/attempt_1/1/error.json
```

**Comment by innerlee** [comment]
Hi how is the mmcv installed?

**Comment by Ha0Tang** [comment]
pip install mmcv-full==1.3.9 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
