### ISSUE TITLE
training basicVSR with REDS failed because of a cv2-error

### ISSUE THREAD

**Issue by rouvaednE** [open-mmlab/mmediting#549]
error log:
2021-09-26 19:36:33,483 - mmedit - INFO - workflow: [('train', 1)], max: 3000 iters
2021-09-26 19:38:30,110 - mmedit - INFO - Iter [100/3000]	lr_generator: 2.493e-05, eta: 0:56:15, time: 1.164, data_time: 0.064, memory: 3541, loss_pix: 0.0351, loss: 0.0351
libpng error: IDAT: CRC error
Traceback (most recent call last):
  File "./tools/train.py", line 146, in <module>
    main()
  File "./tools/train.py", line 142, in main
    meta=meta)
  File "/home/css/Disk/mmediting-master/mmedit/apis/train.py", line 72, in train_model
    meta=meta)
  File "/home/css/Disk/mmediting-master/mmedit/apis/train.py", line 206, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 58, in train
    data_batch = next(data_loader)
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 5.
Original Traceback (most recent call last):
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/css/Disk/mmediting-master/mmedit/datasets/dataset_wrappers.py", line 31, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/home/css/Disk/mmediting-master/mmedit/datasets/base_sr_dataset.py", line 53, in __getitem__
    return self.pipeline(results)
  File "/home/css/Disk/mmediting-master/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/home/css/Disk/mmediting-master/mmedit/datasets/pipelines/loading.py", line 147, in __call__
    channel_order=self.channel_order)  # HWC
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/image/io.py", line 238, in imfrombytes
    cv2.cvtColor(img, cv2.COLOR_BGR2RGB, img)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-l1r0y34w/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Traceback (most recent call last):
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/css/.conda/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=0', './configs/restorers/basicvsr/basicvsr_reds4.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by aRrtTist** [comment]
Hi, I also encountered the same problem, how did you solve it? @rouvaednE
