### ISSUE TITLE
HOW TO TEST my own imgs  using edvr 

### ISSUE THREAD

**Issue by dzz416** [open-mmlab/mmediting#610]
i have set the test config:
 test=dict(
        type=val_dataset_type,
        lq_folder='/home1/dzzHD/MIMO-VRN/datasets/REDS/test/X4',
        gt_folder='/home1/dzzHD/MIMO-VRN/datasets/REDS/test_sharp',
        ann_file='/home1/dzzHD/MIMO-VRN/datasets/REDS/mytest.txt',
        num_input_frames=5,
        pipeline=test_pipeline,
        scale=4,
        val_partition='REDS4',
        test_mode=True),
)

but it has some error:
 

  File "tools/test.py", line 139, in <module>
    main()
  File "tools/test.py", line 102, in main
    save_image=args.save_image)
  File "/home1/dzzHD/mmediting/mmedit/apis/test.py", line 42, in single_gpu_test
    for data in data_loader:
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home1/public/software/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home1/dzzHD/mmediting/mmedit/datasets/base_sr_dataset.py", line 53, in __getitem__
    return self.pipeline(results)
  File "/home1/dzzHD/mmediting/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/home1/dzzHD/mmediting/mmedit/datasets/pipelines/loading.py", line 144, in __call__
    img_bytes = self.file_client.get(filepath)
  File "/home/dzz/.local/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 306, in get
    return self.client.get(filepath)
  File "/home/dzz/.local/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 184, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home1/dzzHD/MIMO-VRN/datasets/REDS/test/X4/000/00000004.png'

my imgs donsent has the 00000004.png ,where it comes from ?

**Comment by ckkelvinchan** [comment]
Hello, you need to download the dataset and put them in the designated folder. 

Please refer to [here](https://github.com/open-mmlab/mmediting/tree/master/tools/data/super-resolution/reds) for the folder structure.

**Comment by dzz416** [comment]
> Hello, you need to download the dataset and put them in the designated folder.
> 
> Please refer to [here](https://github.com/open-mmlab/mmediting/tree/master/tools/data/super-resolution/reds) for the folder structure.

but when i run the test.py ,it still need to set the gt_folder,i want to test some new imgs without HR ,what shou i do ?

**Comment by ckkelvinchan** [comment]
You can use `restoration_video_demo.py`. Let's discuss in #611. I will close this issue now.
