### ISSUE TITLE
training basicVSR with REDS Dataset failed because of a cv2-error

### ISSUE THREAD

**Issue by aRrtTist** [open-mmlab/mmediting#653]
This happens often
```
error log:
libpng error: IDAT: CRC error
Traceback (most recent call last):
File "./tools/train.py", line 146, in
main()
File "./tools/train.py", line 142, in main
meta=meta)
File "/home/css/Disk/mmediting-master/mmedit/apis/train.py", line 72, in train_model
meta=meta)
File "/home/css/Disk/mmediting-master/mmedit/apis/train.py", line 206, in _dist_train
runner.run(data_loaders, cfg.workflow, cfg.total_iters)
File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
iter_runner(iter_loaders[i], **kwargs)
File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 58, in train
data_batch = next(data_loader)
File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 32, in next
data = next(self.iter_loader)
File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in next
data = self._next_data()
File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
return self._process_data(data)
File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
data.reraise()
File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 5.
Original Traceback (most recent call last):
File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
data = fetcher.fetch(index)
File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/css/Disk/mmediting-master/mmedit/datasets/dataset_wrappers.py", line 31, in getitem
return self.dataset[idx % self._ori_len]
File "/home/css/Disk/mmediting-master/mmedit/datasets/base_sr_dataset.py", line 53, in getitem
return self.pipeline(results)
File "/home/css/Disk/mmediting-master/mmedit/datasets/pipelines/compose.py", line 42, in call
data = t(data)
File "/home/css/Disk/mmediting-master/mmedit/datasets/pipelines/loading.py", line 147, in call
channel_order=self.channel_order) # HWC
File "/home/css/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/image/io.py", line 238, in imfrombytes
cv2.cvtColor(img, cv2.COLOR_BGR2RGB, img)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-l1r0y34w/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```
I wrote a simple test script to check the image, but the result shows that there is no problem with the image
``` python
    
    def get(filepath):
        with open(filepath, 'rb') as f:
            value_buf = f.read()
    return value_buf

    basedir = './data/REDS/train_sharp_bicubic/X4'
    n = 0
    error_images = list()
    try:
        for sequence in sorted(os.listdir(basedir)):
            cur_path = os.path.join(basedir, sequence)
            for image in sorted(os.listdir(cur_path)):
                imf_path = os.path.join(cur_path, image)
                print(imf_path)
                img_bytes = get(imf_path)
                img = mmcv.imfrombytes(
                    img_bytes, flag='color',
                    channel_order='rgb')  # HWC
                if img is None:
                    error_images.append(imf_path)
                h, w, c = img.shape
                n += 1
        print(n)
        print(error_images)
    except Exception as e:
        print(e)
```

**Comment by aRrtTist** [comment]
It may be a problem of distributed training. After I choose a single GPU training, there is no abnormality. I hope you guys can provide a solution. I noticed that someone asked the same question before.

**Comment by ckkelvinchan** [comment]
It seems that there are images missing in the folder. 

When you use `for image in sorted(os.listdir(cur_path)):`, you only load images that appear in the folder, and you cannot check whether there are missing images. It is advised to manually loop all the indices (from `000` to `269`, from `00000000.png` to `00000099.png`)

**Comment by aRrtTist** [comment]
I did check that the number of images was 27000, and I downloaded the data set from [here](https://seungjunnah.github.io/Datasets/reds.html) many times, and then processed it through the script `pre_process_reds_dataset.py` you provided. But every time I get an error,I added an error message to the function of reading the image, like this
```python
@PIPELINES.register_module()
class LoadImageFromFileList(LoadImageFromFile):
    """Load image from file list.

    It accepts a list of path and read each frame from each path. A list
    of frames will be returned.

    Args:
        io_backend (str): io backend where images are store. Default: 'disk'.
        key (str): Keys in results to find corresponding path. Default: 'gt'.
        flag (str): Loading flag for images. Default: 'color'.
        channel_order (str): Order of channel, candidates are 'bgr' and 'rgb'.
            Default: 'bgr'.
        save_original_img (bool): If True, maintain a copy of the image in
            `results` dict with name of `f'ori_{key}'`. Default: False.
        kwargs (dict): Args for file client.
    """

    def __call__(self, results):
        """Call function.

        Args:
            results (dict): A dict containing the necessary information and
                data for augmentation.

        Returns:
            dict: A dict containing the processed data and information.
        """

        if self.file_client is None:
            self.file_client = FileClient(self.io_backend, **self.kwargs)
        filepaths = results[f'{self.key}_path']
        if not isinstance(filepaths, list):
            raise TypeError(
                f'filepath should be list, but got {type(filepaths)}')

        filepaths = [str(v) for v in filepaths]

        imgs = []
        shapes = []
        if self.save_original_img:
            ori_imgs = []
        for filepath in filepaths:
            # img_bytes = self.file_client.get(filepath)
            # img = mmcv.imfrombytes(
            #     img_bytes, flag=self.flag,
            #     channel_order=self.channel_order)  # HWC
            # rt ================================
            try:
                img_bytes = self.file_client.get(filepath)
                img = mmcv.imfrombytes(
                    img_bytes, flag=self.flag,
                    channel_order=self.channel_order)  # HWC
            except Exception as e:
                print("======================")
                print(filepath)
                print("======================")
                raise e
            # rt ================================
            if img.ndim == 2:
                img = np.expand_dims(img, axis=2)
            imgs.append(img)
            shapes.append(img.shape)
            if self.save_original_img:
                ori_imgs.append(img.copy())

        results[self.key] = imgs
        results[f'{self.key}_path'] = filepaths
        results[f'{self.key}_ori_shape'] = shapes
        if self.save_original_img:
            results[f'ori_{self.key}'] = ori_imgs

        return results
```
It will always say that a certain image in train_sharp has CRC_ERROR or libpng error: bad adaptive filter value, but I checked with the pngchek command and found that these errored images are all in the correct format.

**Comment by wangruohui** [comment]
Hi, based on your description, an idea to debug is to dump the img_bytes variable when error occurs. You can print the length or/and save the file with open('rb'). This is to clarify this certain image you read in distributed training is exactly the same as what you have checked offline.

**Comment by aRrtTist** [comment]
> Hi, based on your description, an idea to debug is to dump the img_bytes variable when error occurs. You can print the length or/and save the file with open('rb'). This is to clarify this certain image you read in distributed training is exactly the same as what you have checked offline.

It is true that there will be wrong image loading during distributed training, but I don’t know why

**Comment by zengyh1900** [comment]
Please check this issue. @Z-Fran

**Comment by Z-Fran** [comment]
It looks like some errors happened when you preprocessed the dataset.

**Comment by zengyh1900** [comment]
Closing due to inactivity, please reopen if there are any further problems.
