### ISSUE TITLE
using restoration_video_demo.py get Error 'stack expects a non-empty TensorList'

### ISSUE THREAD

**Issue by BertieJim** [open-mmlab/mmediting#670]
Thanx for the brilliant repo!
I've tryed restoration img, works just fine.
When using  restoration_video_demo like this:
`python demo/restoration_video_demo.py ./configs/restorers/edvr/edvrm_wotsa_x4_g8_600k_reds.py https://download.openmmlab.com/mmediting/restorers/edvr/edvrm_wotsa_x4_8x4_600k_reds_20200522-0570e567.pth data/ddd/1639714918327.mp4 ./output --window_size=5`

it said:
```
Use load_from_http loader
{'lq_path': 'data/ddd', 'gt_path': '', 'key': '1639714918327.mp4', 'sequence_length': 0}
Traceback (most recent call last):
  File "demo/restoration_video_demo.py", line 54, in <module>
    main()
  File "demo/restoration_video_demo.py", line 44, in main
    args.filename_tmpl)
  File "/home/jinbo/test/mmediting-master/mmedit/apis/restoration_video_inference.py", line 74, in restoration_video_inference
    data = test_pipeline(data)
  File "/home/jinbo/test/mmediting-master/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/home/jinbo/test/mmediting-master/mmedit/datasets/pipelines/formating.py", line 135, in __call__
    results[key] = torch.stack(results[key], dim=0)
RuntimeError: stack expects a non-empty TensorList
```

When not assing the file name like this:
`python demo/restoration_video_demo.py ./configs/restorers/edvr/edvrm_wotsa_x4_g8_600k_reds.py https://download.openmmlab.com/mmediting/restorers/edvr/edvrm_wotsa_x4_8x4_600k_reds_20200522-0570e567.pth data/ddd/ ./output --window_size=5`

it said:
```
Use load_from_http loader
{'lq_path': 'data/ddd', 'gt_path': '', 'key': '', 'sequence_length': 1}
Traceback (most recent call last):
  File "demo/restoration_video_demo.py", line 54, in <module>
    main()
  File "demo/restoration_video_demo.py", line 44, in main
    args.filename_tmpl)
  File "/home/jinbo/test/mmediting-master/mmedit/apis/restoration_video_inference.py", line 74, in restoration_video_inference
    data = test_pipeline(data)
  File "/home/jinbo/test/mmediting-master/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/home/jinbo/test/mmediting-master/mmedit/datasets/pipelines/loading.py", line 163, in __call__
    img_bytes = self.file_client.get(filepath)
  File "/home/jinbo/.conda/envs/sssssuper/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 306, in get
    return self.client.get(filepath)
  File "/home/jinbo/.conda/envs/sssssuper/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 184, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/ddd/00000000.png'
```

:(

**Comment by BertieJim** [comment]
Hey!
I print the t and data in compose.py __call__

it said:

```
GenerateSegmentIndices(interval_list=[1])
ttt---ttt--ttt
{'lq_path': 'data/ddd', 'gt_path': '', 'key': '1639714918327.mp4', 'sequence_length': 0}
---data----
LoadImageFromFileList(io_backend=disk, key=lq, flag=color, save_original_img=False, channel_order=rgb, use_cache=False)
ttt---ttt--ttt
{'lq_path': [], 'gt_path': [], 'key': '1639714918327.mp4', 'sequence_length': 0, 'interval': 1}
---data----
RescaleToZeroOne(keys=['lq'])
ttt---ttt--ttt
{'lq_path': [], 'gt_path': [], 'key': '1639714918327.mp4', 'sequence_length': 0, 'interval': 1, 'lq': [], 'lq_ori_shape': []}
---data----
FramesToTensor(keys=['lq'], to_float32=True)
ttt---ttt--ttt
{'lq_path': [], 'gt_path': [], 'key': '1639714918327.mp4', 'sequence_length': 0, 'interval': 1, 'lq': [], 'lq_ori_shape': []}
---data----
Traceback (most recent call last):
  File "demo/restoration_video_demo.py", line 54, in <module>
    main()
  File "demo/restoration_video_demo.py", line 44, in main
    args.filename_tmpl)
  File "/home/jinbo/test/mmediting-master/mmedit/apis/restoration_video_inference.py", line 74, in restoration_video_inference
    data = test_pipeline(data)
  File "/home/jinbo/test/mmediting-master/mmedit/datasets/pipelines/compose.py", line 48, in __call__
    data = t(data)
  File "/home/jinbo/test/mmediting-master/mmedit/datasets/pipelines/formating.py", line 135, in __call__
    results[key] = torch.stack(results[key], dim=0)
RuntimeError: stack expects a non-empty TensorList

```

**Comment by ckkelvinchan** [comment]
Hi the current video demo does not support video as input. We are working on it and it will be supported soon! Please refer to #622 for more details.

For now, you can only convert them to images first, and then pass them to the network.

**Comment by BertieJim** [comment]
> Hi the current video demo does not support video as input. We are working on it and it will be supported soon! Please refer to #622 for more details.
> 
> For now, you can only convert them to images first, and then pass them to the network.

thanx a lot.
I am adding that part to the code then run it.
And it just freeze until then.
