### ISSUE TITLE
cannot use TDAN model in restoration_video_demo.py

### ISSUE THREAD

**Issue by zslzx** [open-mmlab/mmediting#747]
I tried to use TDAN model in demo/restoration_video_demo.py, but failed.

Here is my script:

```
model_name=TDAN
model_file=tdan/tdan_vimeo90k_bdx4_ft_lr5e-5_800k.py
model_path=https://download.openmmlab.com/mmediting/restorers/tdan/tdan_vimeo90k_bdx4_20210528-c53ab844.pth

list=(calendar city foliage walk)

for i in ${list[*]}; do
    input_path=./Vid4_gaussian_lr/$i
    output_path=./outputs/${i}
    CUDA_VISIBLE_DEVICES=6 python demo/restoration_video_demo.py ./configs/restorers/$model_file $model_path  $input_path ${output_path}_${model_name}
done
```

And here is the error information:

```
Traceback (most recent call last):
  File "demo/restoration_video_demo.py", line 84, in <module>
    main()
  File "demo/restoration_video_demo.py", line 60, in main
    output = restoration_video_inference(model, args.input_dir,
  File "/home/user1/mmediting/mmediting/mmedit/apis/restoration_video_inference.py", line 119, in restoration_video_inference
    result = model(lq=data, test_mode=True)['output'].cpu()
  File "/home/user1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/home/user1/mmediting/mmediting/mmedit/models/restorers/basic_restorer.py", line 75, in forward
    return self.forward_test(lq, gt, **kwargs)
  File "/home/user1/mmediting/mmediting/mmedit/models/restorers/tdan.py", line 113, in forward_test
    output = self.generator(lq)[0]  # keep only the HR output
  File "/home/user1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user1/mmediting/mmediting/mmedit/models/backbones/sr_backbones/tdan_net.py", line 152, in forward
    return self.reconstruct(aligned_lrs), aligned_lrs.view(n, t, c, h, w)
  File "/home/user1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/user1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 201, in forward
    x = self.conv(x)
  File "/home/user1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/user1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 15, 3, 3], expected input[1, 123, 144, 180] to have 15 channels, but got 123 channels instead
 
```

**Comment by ckkelvinchan** [comment]
As shown here, you need to specify `window_size` for sliding-window methods. Here you should use 5.

![CleanShot 2022-02-20 at 20 31 55](https://user-images.githubusercontent.com/7676947/154842610-c7d976be-e63a-464e-8c13-2e3135d6f991.png)

**Comment by zslzx** [comment]
> As shown here, you need to specify `window_size` for sliding-window methods. Here you should use 5.
> 
> ![CleanShot 2022-02-20 at 20 31 55](https://user-images.githubusercontent.com/7676947/154842610-c7d976be-e63a-464e-8c13-2e3135d6f991.png)

It works. Thanks!
