### ISSUE TITLE
how to find the position of bug when using mmediting

### ISSUE THREAD

**Issue by Lvhhhh** [open-mmlab/mmediting#893]
such as 
Expected: /root/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so to exist.
Expected: /root/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so to exist.
Expected: /root/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so to exist.
Expected: /root/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so to exist.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array
Exception ignored in: <generator object RandomSampler.__iter__ at 0x7f51c1adcbf8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/sampler.py", line 125, in __iter__
  File "/root/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 531, in trace_dispatch
  File "/root/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_collect_try_except_info.py", line 156, in collect_return_info
TypeError: 'NoneType' object is not callable

Process finished with exit code 1

i found it cannot find where the bug is

**Comment by wangruohui** [comment]
seems this may not be related to mmedit itself but pycharm. Would you try run the program from the command line?

**Comment by wangruohui** [comment]
The call stack seems to be:

(something related to pycharm)
File "/root/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 531, in trace_dispatch
File "/root/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_collect_try_except_info.py", line 156, in collect_return_info

(RandomSampler of Pytorch)
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/sampler.py", line 125, in iter

(Something about numpy)
File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc

Then maybe it calls some method 
> return getattr(obj, method)(*args, **kwds)

But this function is compiled in some dynamic library (.so) file, so
> Expected: /root/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so to exist.

I think you can further try modify the number of workers of the dataloader (workers_per_gpu in the config file) to 0. So maybe you can get a more completed traceback log.
