### ISSUE TITLE
GLEAN model test--Spatial resolution must equal in_size (32)

### ISSUE THREAD

**Issue by zhangjiarui130** [open-mmlab/mmediting#900]
1. 测试命令行
python demo/restoration_demo.py configs/restorers/glean/glean_cat_8x.py checkpoint/glean_cat_8x_20210614-d3ac8683.pth ./pic/csmz2_2s_540p/00000000.png ./zjrout/picSuper/00000000_glean_8x.png --device 3
2. 报错信息
AssertionError: Spatial resolution must equal in_size (32). Got (1080, 1920)

**Comment by zhangjiarui130** [comment]
Traceback (most recent call last):
  File "demo/restoration_demo.py", line 62, in <module>
    main()
  File "demo/restoration_demo.py", line 53, in main
    output = restoration_inference(model, args.img_path)
  File "/home/pc/zyp/mmediting-master/mmedit/apis/restoration_inference.py", line 46, in restoration_inference
    result = model(test_mode=True, **data)
  File "/home/pc/anaconda3/envs/mmedit/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pc/anaconda3/envs/mmedit/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/home/pc/zyp/mmediting-master/mmedit/models/restorers/srgan.py", line 95, in forward
    return self.forward_test(lq, gt, **kwargs)
  File "/home/pc/zyp/mmediting-master/mmedit/models/restorers/glean.py", line 54, in forward_test
    output = self.generator(lq)
  File "/home/pc/anaconda3/envs/mmedit/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pc/zyp/mmediting-master/mmedit/models/backbones/sr_backbones/glean_styleganv2.py", line 209, in forward
    raise AssertionError(
AssertionError: Spatial resolution must equal in_size (32). Got (1080, 1920).

**Comment by wangruohui** [comment]
Hello, 

The size of the image should be 32x32 but you use a 1080x1920 one. The desired size of the model is indicated in the config file by key `model.generator.in_size`.
