### ISSUE TITLE
Error to convert VSR ONNX model with pytorch2onnx.py

### ISSUE THREAD

**Issue by T1M-CHEN** [open-mmlab/mmediting#902]
Hello, thanks to your great work.
I encounter difficulties when converting VSR model to ONNX.

`Environment`:
I follow the tutorial `demo/restorer_basic_tutorial_zh-CN.ipynb` and run on Kaggle environment.

Command in jupyter:
```bash
# BasicVSR
!python tools/pytorch2onnx.py ./configs/restorers/basicvsr/basicvsr_reds4.py \
https://download.openmmlab.com/mmediting/restorers/basicvsr/basicvsr_reds4_20120409-0e599677.pth \
restorer \
./demo_files/lq_images/baby.png \
--output-file BasicVSR.onnx
```
Error message:
```
2022-05-29 03:07:35,404 - mmedit - INFO - load checkpoint from http path: https://download.openmmlab.com/mmediting/restorers/basicvsr/spynet_20210409-c6c1bd09.pth
load checkpoint from http path: https://download.openmmlab.com/mmediting/restorers/basicvsr/basicvsr_reds4_20120409-0e599677.pth
The model and loaded state dict do not match exactly

missing keys in source state_dict: step_counter

Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 195, in <module>
    data = test_pipeline(data)
  File "/kaggle/working/mmediting/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/kaggle/working/mmediting/mmedit/datasets/pipelines/augmentation.py", line 1090, in __call__
    clip_name = results['key']
KeyError: 'key'
```

Maybe VSR model requires sequences images as input, but `pytorch2onnx.py` just supports to have single image as input? Since from wiki convert SR models to ONNX is supported.

Thanks.

**Comment by w5688414** [comment]
I also met the same problem, how to resolve it?
