### ISSUE TITLE
TypeError: 'DataContainer' object is not subscriptable

### ISSUE THREAD

**Issue by 1738328987** [open-mmlab/mmediting#962]
在命令行中启用如下:python demo/matting_demo.py  configs/mattors/dim/dim_stage3_v16_pln_1x1_1000k_comp1k.py work_dirs/dim_stage3/latest.pth tests/data/merged/GT05.jpg tests/data/trimap/GT05.png tests/data/pred/GT05.png
报出如图错误:
![image](https://user-images.githubusercontent.com/45223697/179825100-dfdd4c70-0752-412d-8d46-ac9b6522447d.png)

另外我使用的work_dirs/dim_stage3/latest.pth这个latest.pth是来自于
![image](https://user-images.githubusercontent.com/45223697/179825581-de7ce4d0-23eb-4321-8e3b-6c6f3e0c8b0f.png)
不知道是否是此pth造成的问题,刚入行,还请见谅不知道如何获取pth文件,提供的源码也没有此文件,还有文档中的data文件夹也没有

**Comment by wangruohui** [comment]
pth 文件单击即可下载，放到work_dirs/dim_stage3/latest.pth这个位置即可，或放到其他位置并对应修改命令行，你这个已经跑起来了应该是正确处理的。

另外我尝试了下你的命令没有报错，可以正常运行，请问你使用的mmedit版本和mmcv版本分别是多少？

**Comment by zengyh1900** [comment]
Closing due to inactivity, please reopen if there are any further problems.

**Comment by buguaigiser** [comment]
请问解决了吗？

**Comment by changqing91** [comment]
mmediting % python demo/matting_demo.py \
    configs/mattors/dim/dim_stage3_v16_pln_1x1_1000k_comp1k.py \
    work_dirs/dim_stage3/latest.pth \
    tests/data/merged/GT05.jpg \
    tests/data/trimap/GT05.png \
    tests/data/pred/GT05.png

Then i got: 

load checkpoint from local path: work_dirs/dim_stage3/latest.pth
Traceback (most recent call last):
  File "/Users/changqing/Github/mmediting/demo/matting_demo.py", line 43, in <module>
    main()
  File "/Users/changqing/Github/mmediting/demo/matting_demo.py", line 34, in main
    pred_alpha = matting_inference(model, args.img_path,
  File "/Users/changqing/Github/mmediting/mmedit/apis/matting_inference.py", line 76, in matting_inference
    result = model(test_mode=True, **data)
  File "/Users/changqing/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/changqing/Github/mmediting/mmedit/models/mattors/base_mattor.py", line 263, in forward
    return self.forward_test(merged, trimap, meta, **kwargs)
  File "/Users/changqing/Github/mmediting/mmedit/models/mattors/dim.py", line 153, in forward_test
    pred_alpha = self.restore_shape(pred_alpha, meta)
  File "/Users/changqing/Github/mmediting/mmedit/models/mattors/base_mattor.py", line 130, in restore_shape
    ori_trimap = meta[0]['ori_trimap'].squeeze()
TypeError: 'DataContainer' object is not subscriptable
(base) changqing@GreendeMacBook-Pro mmediting %
