### ISSUE TITLE
视频超分辨率 测试报错  Video super-resolution test error

### ISSUE THREAD

**Issue by xiaoyaozihe** [open-mmlab/mmediting#983]
Traceback (most recent call last):
  File "mmediting/demo/video_interpolation_demo.py", line 97, in <module>
    main()
  File "mmediting/demo/video_interpolation_demo.py", line 84, in main
    video_interpolation_inference(
  File "mmediting\mmedit\apis\video_interpolation_inference.py", line 153, in video_interpolation_inference
    step_size = model.step_frames * batch_size
  File "C:\ProgramData\Miniconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BasicVSR' object has no attribute 'step_frames'

**Comment by xiaoyaozihe** [comment]
Config file 
../configs/restorers/basicvsr_plusplus/basicvsr_plusplus_c64n7_8x1_600k_reds4.py
../tools/work_dirs/basicvsr_plusplus_c64n7_8x1_600k_reds4/basicvsr_plusplus_c64n7_8x1_600k_reds4_20210217-db622b2f.pth

**Comment by xiaoyaozihe** [comment]
我自己搞错了 应该是 用“restoration_video_demo.py”，我之前是用这个测试“video_interpolation_demo.py” 这个是视频插帧的

I made a mistake. It should be "restoration_video_demo.py". I used this test before to test "video_interpolation_demo.py". This is video interpolation
